#ifndef LENS_ICON_H
#define LENS_ICON_H

#include <stdint.h>

/* Single source of truth for LENS_API — never restate it here. */
#include <lens/export.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum lens_icon_id {
    LENS_ICON_ACTIVITY = 0,
    LENS_ICON_AIRPLAY = 1,
    LENS_ICON_ALERT_CIRCLE = 2,
    LENS_ICON_ALERT_OCTAGON = 3,
    LENS_ICON_ALERT_TRIANGLE = 4,
    LENS_ICON_ALIGN_CENTER = 5,
    LENS_ICON_ALIGN_JUSTIFY = 6,
    LENS_ICON_ALIGN_LEFT = 7,
    LENS_ICON_ALIGN_RIGHT = 8,
    LENS_ICON_ANCHOR = 9,
    LENS_ICON_APERTURE = 10,
    LENS_ICON_ARCHIVE = 11,
    LENS_ICON_ARROW_DOWN_CIRCLE = 12,
    LENS_ICON_ARROW_DOWN_LEFT = 13,
    LENS_ICON_ARROW_DOWN_RIGHT = 14,
    LENS_ICON_ARROW_DOWN = 15,
    LENS_ICON_ARROW_LEFT_CIRCLE = 16,
    LENS_ICON_ARROW_LEFT = 17,
    LENS_ICON_ARROW_RIGHT_CIRCLE = 18,
    LENS_ICON_ARROW_RIGHT = 19,
    LENS_ICON_ARROW_UP_CIRCLE = 20,
    LENS_ICON_ARROW_UP_LEFT = 21,
    LENS_ICON_ARROW_UP_RIGHT = 22,
    LENS_ICON_ARROW_UP = 23,
    LENS_ICON_AT_SIGN = 24,
    LENS_ICON_AWARD = 25,
    LENS_ICON_BAR_CHART_2 = 26,
    LENS_ICON_BAR_CHART = 27,
    LENS_ICON_BATTERY_CHARGING = 28,
    LENS_ICON_BATTERY = 29,
    LENS_ICON_BELL_OFF = 30,
    LENS_ICON_BELL = 31,
    LENS_ICON_BLUETOOTH = 32,
    LENS_ICON_BOLD = 33,
    LENS_ICON_BOOK_OPEN = 34,
    LENS_ICON_BOOK = 35,
    LENS_ICON_BOOKMARK = 36,
    LENS_ICON_BOX = 37,
    LENS_ICON_BRIEFCASE = 38,
    LENS_ICON_CALENDAR = 39,
    LENS_ICON_CAMERA_OFF = 40,
    LENS_ICON_CAMERA = 41,
    LENS_ICON_CAST = 42,
    LENS_ICON_CHECK_CIRCLE = 43,
    LENS_ICON_CHECK_SQUARE = 44,
    LENS_ICON_CHECK = 45,
    LENS_ICON_CHEVRON_DOWN = 46,
    LENS_ICON_CHEVRON_LEFT = 47,
    LENS_ICON_CHEVRON_RIGHT = 48,
    LENS_ICON_CHEVRON_UP = 49,
    LENS_ICON_CHEVRONS_DOWN = 50,
    LENS_ICON_CHEVRONS_LEFT = 51,
    LENS_ICON_CHEVRONS_RIGHT = 52,
    LENS_ICON_CHEVRONS_UP = 53,
    LENS_ICON_CHROME = 54,
    LENS_ICON_CIRCLE = 55,
    LENS_ICON_CLIPBOARD = 56,
    LENS_ICON_CLOCK = 57,
    LENS_ICON_CLOUD_DRIZZLE = 58,
    LENS_ICON_CLOUD_LIGHTNING = 59,
    LENS_ICON_CLOUD_OFF = 60,
    LENS_ICON_CLOUD_RAIN = 61,
    LENS_ICON_CLOUD_SNOW = 62,
    LENS_ICON_CLOUD = 63,
    LENS_ICON_CODE = 64,
    LENS_ICON_CODEPEN = 65,
    LENS_ICON_CODESANDBOX = 66,
    LENS_ICON_COFFEE = 67,
    LENS_ICON_COLUMNS = 68,
    LENS_ICON_COMMAND = 69,
    LENS_ICON_COMPASS = 70,
    LENS_ICON_COPY = 71,
    LENS_ICON_CORNER_DOWN_LEFT = 72,
    LENS_ICON_CORNER_DOWN_RIGHT = 73,
    LENS_ICON_CORNER_LEFT_DOWN = 74,
    LENS_ICON_CORNER_LEFT_UP = 75,
    LENS_ICON_CORNER_RIGHT_DOWN = 76,
    LENS_ICON_CORNER_RIGHT_UP = 77,
    LENS_ICON_CORNER_UP_LEFT = 78,
    LENS_ICON_CORNER_UP_RIGHT = 79,
    LENS_ICON_CPU = 80,
    LENS_ICON_CREDIT_CARD = 81,
    LENS_ICON_CROP = 82,
    LENS_ICON_CROSSHAIR = 83,
    LENS_ICON_DATABASE = 84,
    LENS_ICON_DELETE = 85,
    LENS_ICON_DISC = 86,
    LENS_ICON_DIVIDE_CIRCLE = 87,
    LENS_ICON_DIVIDE_SQUARE = 88,
    LENS_ICON_DIVIDE = 89,
    LENS_ICON_DOLLAR_SIGN = 90,
    LENS_ICON_DOWNLOAD_CLOUD = 91,
    LENS_ICON_DOWNLOAD = 92,
    LENS_ICON_DRIBBBLE = 93,
    LENS_ICON_DROPLET = 94,
    LENS_ICON_EDIT_2 = 95,
    LENS_ICON_EDIT_3 = 96,
    LENS_ICON_EDIT = 97,
    LENS_ICON_EXTERNAL_LINK = 98,
    LENS_ICON_EYE_OFF = 99,
    LENS_ICON_EYE = 100,
    LENS_ICON_FACEBOOK = 101,
    LENS_ICON_FAST_FORWARD = 102,
    LENS_ICON_FEATHER = 103,
    LENS_ICON_FIGMA = 104,
    LENS_ICON_FILE_MINUS = 105,
    LENS_ICON_FILE_PLUS = 106,
    LENS_ICON_FILE_TEXT = 107,
    LENS_ICON_FILE = 108,
    LENS_ICON_FILM = 109,
    LENS_ICON_FILTER = 110,
    LENS_ICON_FLAG = 111,
    LENS_ICON_FOLDER_MINUS = 112,
    LENS_ICON_FOLDER_PLUS = 113,
    LENS_ICON_FOLDER = 114,
    LENS_ICON_FRAMER = 115,
    LENS_ICON_FROWN = 116,
    LENS_ICON_GIFT = 117,
    LENS_ICON_GIT_BRANCH = 118,
    LENS_ICON_GIT_COMMIT = 119,
    LENS_ICON_GIT_MERGE = 120,
    LENS_ICON_GIT_PULL_REQUEST = 121,
    LENS_ICON_GITHUB = 122,
    LENS_ICON_GITLAB = 123,
    LENS_ICON_GLOBE = 124,
    LENS_ICON_GRID = 125,
    LENS_ICON_HARD_DRIVE = 126,
    LENS_ICON_HASH = 127,
    LENS_ICON_HEADPHONES = 128,
    LENS_ICON_HEART = 129,
    LENS_ICON_HELP_CIRCLE = 130,
    LENS_ICON_HEXAGON = 131,
    LENS_ICON_HOME = 132,
    LENS_ICON_IMAGE = 133,
    LENS_ICON_INBOX = 134,
    LENS_ICON_INFO = 135,
    LENS_ICON_INSTAGRAM = 136,
    LENS_ICON_ITALIC = 137,
    LENS_ICON_KEY = 138,
    LENS_ICON_LAYERS = 139,
    LENS_ICON_LAYOUT = 140,
    LENS_ICON_LIFE_BUOY = 141,
    LENS_ICON_LINK_2 = 142,
    LENS_ICON_LINK = 143,
    LENS_ICON_LINKEDIN = 144,
    LENS_ICON_LIST = 145,
    LENS_ICON_LOADER = 146,
    LENS_ICON_LOCK = 147,
    LENS_ICON_LOG_IN = 148,
    LENS_ICON_LOG_OUT = 149,
    LENS_ICON_MAIL = 150,
    LENS_ICON_MAP_PIN = 151,
    LENS_ICON_MAP = 152,
    LENS_ICON_MAXIMIZE_2 = 153,
    LENS_ICON_MAXIMIZE = 154,
    LENS_ICON_MEH = 155,
    LENS_ICON_MENU = 156,
    LENS_ICON_MESSAGE_CIRCLE = 157,
    LENS_ICON_MESSAGE_SQUARE = 158,
    LENS_ICON_MIC_OFF = 159,
    LENS_ICON_MIC = 160,
    LENS_ICON_MINIMIZE_2 = 161,
    LENS_ICON_MINIMIZE = 162,
    LENS_ICON_MINUS_CIRCLE = 163,
    LENS_ICON_MINUS_SQUARE = 164,
    LENS_ICON_MINUS = 165,
    LENS_ICON_MONITOR = 166,
    LENS_ICON_MOON = 167,
    LENS_ICON_MORE_HORIZONTAL = 168,
    LENS_ICON_MORE_VERTICAL = 169,
    LENS_ICON_MOUSE_POINTER = 170,
    LENS_ICON_MOVE = 171,
    LENS_ICON_MUSIC = 172,
    LENS_ICON_NAVIGATION_2 = 173,
    LENS_ICON_NAVIGATION = 174,
    LENS_ICON_OCTAGON = 175,
    LENS_ICON_PACKAGE = 176,
    LENS_ICON_PAPERCLIP = 177,
    LENS_ICON_PAUSE_CIRCLE = 178,
    LENS_ICON_PAUSE = 179,
    LENS_ICON_PEN_TOOL = 180,
    LENS_ICON_PERCENT = 181,
    LENS_ICON_PHONE_CALL = 182,
    LENS_ICON_PHONE_FORWARDED = 183,
    LENS_ICON_PHONE_INCOMING = 184,
    LENS_ICON_PHONE_MISSED = 185,
    LENS_ICON_PHONE_OFF = 186,
    LENS_ICON_PHONE_OUTGOING = 187,
    LENS_ICON_PHONE = 188,
    LENS_ICON_PIE_CHART = 189,
    LENS_ICON_PLAY_CIRCLE = 190,
    LENS_ICON_PLAY = 191,
    LENS_ICON_PLUS_CIRCLE = 192,
    LENS_ICON_PLUS_SQUARE = 193,
    LENS_ICON_PLUS = 194,
    LENS_ICON_POCKET = 195,
    LENS_ICON_POWER = 196,
    LENS_ICON_PRINTER = 197,
    LENS_ICON_RADIO = 198,
    LENS_ICON_REFRESH_CCW = 199,
    LENS_ICON_REFRESH_CW = 200,
    LENS_ICON_REPEAT = 201,
    LENS_ICON_REWIND = 202,
    LENS_ICON_ROTATE_CCW = 203,
    LENS_ICON_ROTATE_CW = 204,
    LENS_ICON_RSS = 205,
    LENS_ICON_SAVE = 206,
    LENS_ICON_SCISSORS = 207,
    LENS_ICON_SEARCH = 208,
    LENS_ICON_SEND = 209,
    LENS_ICON_SERVER = 210,
    LENS_ICON_SETTINGS = 211,
    LENS_ICON_SHARE_2 = 212,
    LENS_ICON_SHARE = 213,
    LENS_ICON_SHIELD_OFF = 214,
    LENS_ICON_SHIELD = 215,
    LENS_ICON_SHOPPING_BAG = 216,
    LENS_ICON_SHOPPING_CART = 217,
    LENS_ICON_SHUFFLE = 218,
    LENS_ICON_SIDEBAR = 219,
    LENS_ICON_SKIP_BACK = 220,
    LENS_ICON_SKIP_FORWARD = 221,
    LENS_ICON_SLACK = 222,
    LENS_ICON_SLASH = 223,
    LENS_ICON_SLIDERS = 224,
    LENS_ICON_SMARTPHONE = 225,
    LENS_ICON_SMILE = 226,
    LENS_ICON_SPEAKER = 227,
    LENS_ICON_SQUARE = 228,
    LENS_ICON_STAR = 229,
    LENS_ICON_STOP_CIRCLE = 230,
    LENS_ICON_SUN = 231,
    LENS_ICON_SUNRISE = 232,
    LENS_ICON_SUNSET = 233,
    LENS_ICON_TABLE = 234,
    LENS_ICON_TABLET = 235,
    LENS_ICON_TAG = 236,
    LENS_ICON_TARGET = 237,
    LENS_ICON_TERMINAL = 238,
    LENS_ICON_THERMOMETER = 239,
    LENS_ICON_THUMBS_DOWN = 240,
    LENS_ICON_THUMBS_UP = 241,
    LENS_ICON_TOGGLE_LEFT = 242,
    LENS_ICON_TOGGLE_RIGHT = 243,
    LENS_ICON_TOOL = 244,
    LENS_ICON_TRASH_2 = 245,
    LENS_ICON_TRASH = 246,
    LENS_ICON_TRELLO = 247,
    LENS_ICON_TRENDING_DOWN = 248,
    LENS_ICON_TRENDING_UP = 249,
    LENS_ICON_TRIANGLE = 250,
    LENS_ICON_TRUCK = 251,
    LENS_ICON_TV = 252,
    LENS_ICON_TWITCH = 253,
    LENS_ICON_TWITTER = 254,
    LENS_ICON_TYPE = 255,
    LENS_ICON_UMBRELLA = 256,
    LENS_ICON_UNDERLINE = 257,
    LENS_ICON_UNLOCK = 258,
    LENS_ICON_UPLOAD_CLOUD = 259,
    LENS_ICON_UPLOAD = 260,
    LENS_ICON_USER_CHECK = 261,
    LENS_ICON_USER_MINUS = 262,
    LENS_ICON_USER_PLUS = 263,
    LENS_ICON_USER_X = 264,
    LENS_ICON_USER = 265,
    LENS_ICON_USERS = 266,
    LENS_ICON_VIDEO_OFF = 267,
    LENS_ICON_VIDEO = 268,
    LENS_ICON_VOICEMAIL = 269,
    LENS_ICON_VOLUME_1 = 270,
    LENS_ICON_VOLUME_2 = 271,
    LENS_ICON_VOLUME_X = 272,
    LENS_ICON_VOLUME = 273,
    LENS_ICON_WATCH = 274,
    LENS_ICON_WIFI_OFF = 275,
    LENS_ICON_WIFI = 276,
    LENS_ICON_WIND = 277,
    LENS_ICON_X_CIRCLE = 278,
    LENS_ICON_X_OCTAGON = 279,
    LENS_ICON_X_SQUARE = 280,
    LENS_ICON_X = 281,
    LENS_ICON_YOUTUBE = 282,
    LENS_ICON_ZAP_OFF = 283,
    LENS_ICON_ZAP = 284,
    LENS_ICON_ZOOM_IN = 285,
    LENS_ICON_ZOOM_OUT = 286,
    LENS_ICON_STAR_ROUNDED_FILLED = 287,
    LENS_ICON_STAR_ROUNDED = 288,
    LENS_ICON_COUNT,
} lens_icon_id;

typedef struct lens_icon_cmd {
    uint8_t type;
    float params[6];
} lens_icon_cmd;

/* A contiguous sub-range of a lens_icon_desc's cmd stream painted with its
 * own colour and mode. `color` is a straight (non-premultiplied)
 * 0xRRGGBBAA value; `fill` selects fill_path vs stroke_path for the range.
 * Runtime SVG registration (lens_icon_register_svg) produces one run per
 * source shape, preserving the SVG's paint colours; `runs == NULL` on a
 * desc means "single paint for the whole stream" (every built-in icon) and
 * the draw colour comes from the widget/theme as before. */
typedef struct lens_icon_run {
    uint32_t first_cmd; /* index into cmds */
    uint32_t count;     /* number of cmds in this run */
    uint32_t color;     /* 0xRRGGBBAA, straight alpha */
    uint8_t fill;       /* 1 = fill, 0 = stroke */
    uint8_t reserved[3];
} lens_icon_run;

typedef struct lens_icon_desc {
    const lens_icon_cmd *cmds;
    uint32_t count;
    const lens_icon_run *runs;     /* NULL = whole stream, one theme paint */
    uint32_t run_count;            /* 0 unless runs != NULL */
} lens_icon_desc;

/* The built-in icon table is internal: lens_icon_id values < LENS_ICON_COUNT
 * index it, and lens_icon_info() is the public read access. It is not part
 * of the installed API surface. */

/* Failure sentinel of lens_icon_register_svg; also usable as a "no icon"
 * value wherever a lens_icon_id is optional. */
#define LENS_ICON_INVALID ((lens_icon_id) - 1)

/* Register an SVG string as a runtime icon. Returns its id (>= LENS_ICON_COUNT)
 * or LENS_ICON_INVALID on parse failure. Ids are process-global, never reclaimed;
 * call from the UI thread (registration is not thread-safe, like the rest of lens).
 *
 * Shapes painted `currentColor` (or with no paint attribute) follow the theme
 * colour exactly like built-ins. Shapes carrying an explicit colour keep it:
 * registration records one paint run per shape with its fill/stroke colour
 * (0xRRGGBBAA). Gradients degrade to the gradient's first stop colour.
 * The source strokeWidth is still not honoured — one weight keeps runtime
 * icons visually interchangeable with the built-in set; a shape with both
 * fill and stroke contributes its fill run (stroke-on-fill outlines can be
 * expressed by duplicating the shape). */
LENS_API lens_icon_id lens_icon_register_svg(const char *svg_utf8);

#ifdef __cplusplus
}
#endif

#endif
