/*
 * Image-domain effects. v1 ships the Gaussian blur operator (see
 * ADR-0008). Module state hangs off flux_device via the same
 * pattern the canvas module uses (ADR-0002): a typed pointer + a
 * destroy callback set lazily on first use.
 *
 * Layout in this file:
 *   - module state struct + per-device init/destroy
 *   - transient-image pool (intermediate cache + output list)
 *   - compute pipeline lazy-build (single shader, axis push-const)
 *   - flux_effect_blur exact Gaussian entry point
 *   - fixed-cost multi-resolution filter for animated backdrops
 */

#include "../compute/internal.h"    /* flux_compute_pipeline_make_device_weak */
#include "../core/image_internal.h" /* struct flux_image layout */
#include "../core/internal.h"
#include <flux/compute.h>
#include <flux/effect.h>
#include <flux/vulkan.h>

#include <math.h>
#include <stdalign.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

/* Shader bytecode: C23 #embed, or generated headers (tools/spv2h.py)
 * where the compiler lacks it — see renderer.c for the full rationale. */
#if defined(__has_embed) && !defined(FLUX_SHADER_NO_EMBED)
#if __has_embed("effect_blur.comp.spv") && __has_embed("effect_backdrop.comp.spv") &&            \
    __has_embed("effect_blur_16f.comp.spv") && __has_embed("effect_backdrop_16f.comp.spv")
#define FLUX_EFFECT_SHADERS_EMBED 1
#endif
#endif

#ifdef FLUX_EFFECT_SHADERS_EMBED
alignas(uint32_t) static const unsigned char effect_blur_spv[] = {
#embed "effect_blur.comp.spv"
};

alignas(uint32_t) static const unsigned char effect_backdrop_spv[] = {
#embed "effect_backdrop.comp.spv"
};

/* ADR-0069: rgba16f storage variants for 16F working-space content. */
alignas(uint32_t) static const unsigned char effect_blur_16f_spv[] = {
#embed "effect_blur_16f.comp.spv"
};

alignas(uint32_t) static const unsigned char effect_backdrop_16f_spv[] = {
#embed "effect_backdrop_16f.comp.spv"
};
#else
#include "effect_backdrop_16f_spv.h"
#include "effect_backdrop_spv.h"
#include "effect_blur_16f_spv.h"
#include "effect_blur_spv.h" /* generated by tools/spv2h.py; same arrays */
#endif

/* See renderer.c: ties this TU's ccache key to the shader bytes. */
#include "flux_shader_manifest.h"
static_assert(sizeof(flux_shader_manifest) != 0, "shader manifest");

/* Push-constant block — must match the layout in effect_blur.comp. */
typedef struct effect_blur_push {
    uint32_t in_handle;
    uint32_t sampler_handle;
    uint32_t out_handle;
    uint32_t width;
    uint32_t height;
    int32_t radius;
    float sigma;
    uint32_t axis; /* 0 horizontal, 1 vertical */
} effect_blur_push;

/* Push-constant block — must match the layout in effect_backdrop.comp. */
typedef struct effect_backdrop_push {
    uint32_t in_handle;
    uint32_t sampler_handle;
    uint32_t out_handle;
    uint32_t input_width;
    uint32_t input_height;
    uint32_t output_width;
    uint32_t output_height;
    float offset;
    uint32_t mode; /* 0 downsample, 1 upsample, 2 copy */
    uint32_t origin_x;
    uint32_t origin_y;
    uint32_t region_width;
    uint32_t region_height;
} effect_backdrop_push;

static_assert(sizeof(effect_blur_push) <= FLUX_DEVICE_REQUIRED_PUSH_BYTES,
              "effect_blur_push exceeds device-wide push budget");
static_assert(sizeof(flux_effect_blur_desc) == 32,
              "flux_effect_blur_desc ABI size changed; use its next chain instead");
static_assert(sizeof(flux_effect_blur_regions_desc) == 32,
              "flux_effect_blur_regions_desc ABI layout changed unexpectedly");
static_assert(sizeof(effect_backdrop_push) <= FLUX_DEVICE_REQUIRED_PUSH_BYTES,
              "effect_backdrop_push exceeds device-wide push budget");
static_assert(sizeof(effect_backdrop_push) == 52,
              "effect_backdrop_push no longer matches its shader block");
static_assert(offsetof(effect_backdrop_push, origin_x) == 36,
              "effect_backdrop_push origin no longer matches its shader block");
static_assert(offsetof(effect_backdrop_push, region_height) == 48,
              "effect_backdrop_push region no longer matches its shader block");

#define EFFECT_BLUR_WG 16u
#define EFFECT_BLUR_RADIUS_MAX 64

/* ------------------------------------------------------------------ */
/*  Module state                                                      */
/* ------------------------------------------------------------------ */

/* Cached intermediate target keyed by (format, width, height). One
 * intermediate per key is enough — the horizontal pass writes it,
 * the vertical pass reads it, and the two passes are serialised
 * within a single flux_effect_blur call. Callers issuing concurrent
 * blurs on the same device are already required to serialise per
 * the header doc. */
typedef struct intermediate_entry {
    uint32_t width;
    uint32_t height;
    flux_format format;
    flux_image *image;
    bool leased;
    struct intermediate_entry *next;
} intermediate_entry;

/* Intermediate and output slots are exclusively leased within one reset epoch.
 * They are returned to the pool only at a caller-proven GPU quiescent point. */
typedef struct output_entry {
    uint32_t width;
    uint32_t height;
    flux_format format;
    flux_image *image;
    bool leased;
    struct output_entry *next;
} output_entry;

typedef struct effect_state {
    flux_platform_mutex lock;
    /* Pipeline slots, indexed by storage class: [0] rgba8, [1] rgba16f
     * (ADR-0069: 16F for working-space content when the device
     * advertises rgba16f storage). Lazily built; shared across calls. */
    flux_compute_pipeline *blur_pipelines[2];
    flux_compute_pipeline *backdrop_pipelines[2]; /* fixed-cost live-compositor filter */
    bool storage_16f_supported; /* VK_FORMAT_R16G16B16A16_SFLOAT STORAGE_IMAGE */
    intermediate_entry *intermediates;
    output_entry *outputs;
} effect_state;

typedef struct blur_filter_slot {
    uint32_t width;
    uint32_t height;
    flux_format format;
    flux_image *half;
    flux_image *quarter;
    flux_image *output;
} blur_filter_slot;

struct flux_blur_filter {
    atomic_uint ref_count;
    flux_device *device; /* retained; slot images hold weak device refs */
    blur_filter_slot slots[FLUX_MAX_FRAMES_IN_FLIGHT];
};

static void effect_state_destroy(flux_device *d) {
    effect_state *st = d->effect_state;
    if (!st)
        return;

    for (output_entry *o = st->outputs; o;) {
        output_entry *next = o->next;
        if (o->image)
            flux_image_release(o->image);
        flux_internal_free(d, o);
        o = next;
    }
    for (intermediate_entry *e = st->intermediates; e;) {
        intermediate_entry *next = e->next;
        if (e->image)
            flux_image_release(e->image);
        flux_internal_free(d, e);
        e = next;
    }
    if (st->blur_pipelines[0])
        flux_compute_pipeline_release(st->blur_pipelines[0]);
    if (st->blur_pipelines[1])
        flux_compute_pipeline_release(st->blur_pipelines[1]);
    if (st->backdrop_pipelines[0])
        flux_compute_pipeline_release(st->backdrop_pipelines[0]);
    if (st->backdrop_pipelines[1])
        flux_compute_pipeline_release(st->backdrop_pipelines[1]);
    flux_platform_mutex_destroy(&st->lock);
    flux_internal_free(d, st);
    d->effect_state = nullptr;
    d->effect_state_destroy = nullptr;
}

static effect_state *effect_state_get_or_init(flux_device *d) {
    flux_platform_mutex_lock(&d->module_state_lock);
    effect_state *published = d->effect_state;
    flux_platform_mutex_unlock(&d->module_state_lock);
    if (published)
        return published;

    effect_state *candidate = flux_internal_alloc(d, sizeof(*candidate));
    if (!candidate)
        return nullptr;
    if (!flux_platform_mutex_init(&candidate->lock)) {
        flux_internal_free(d, candidate);
        return nullptr;
    }
    /* rgba16f storage is an optional format feature; resolve once per
     * device (ADR-0069's "effects accept 16F when the device advertises
     * the format features"). */
    {
        VkFormatProperties props;
        vkGetPhysicalDeviceFormatProperties(d->physical_device,
                                            VK_FORMAT_R16G16B16A16_SFLOAT, &props);
        candidate->storage_16f_supported =
            (props.optimalTilingFeatures & VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT) != 0;
    }

    flux_platform_mutex_lock(&d->module_state_lock);
    if (!d->effect_state) {
        d->effect_state = candidate;
        d->effect_state_destroy = effect_state_destroy;
        published = candidate;
        candidate = nullptr;
    } else {
        published = d->effect_state;
    }
    flux_platform_mutex_unlock(&d->module_state_lock);

    if (candidate) {
        flux_platform_mutex_destroy(&candidate->lock);
        flux_internal_free(d, candidate);
    }
    return published;
}

/* ------------------------------------------------------------------ */
/*  Transient acquisition                                             */
/* ------------------------------------------------------------------ */

/* Look up or allocate the intermediate for this key. Returned image
 * is owned by the pool and lives until reset. */
static flux_result acquire_intermediate(flux_device *d, effect_state *st, uint32_t w, uint32_t h,
                                        flux_format fmt, flux_image **out,
                                        intermediate_entry **out_lease) {
    for (intermediate_entry *e = st->intermediates; e; e = e->next) {
        if (!e->leased && e->width == w && e->height == h && e->format == fmt) {
            e->leased = true;
            *out = e->image;
            *out_lease = e;
            return FLUX_OK;
        }
    }
    flux_image *img = nullptr;
    flux_result r = flux_image_create_compute_writable(d, w, h, fmt, &img);
    if (r != FLUX_OK)
        return r;

    intermediate_entry *e = flux_internal_alloc(d, sizeof(*e));
    if (!e) {
        flux_image_release(img);
        return FLUX_ERROR_OUT_OF_MEMORY;
    }
    e->width = w;
    e->height = h;
    e->format = fmt;
    e->image = img;
    e->leased = true;
    e->next = st->intermediates;
    st->intermediates = e;
    *out = img;
    *out_lease = e;
    return FLUX_OK;
}

/* Lease a same-key output, growing the pool to the epoch high-water mark. */
static flux_result acquire_output(flux_device *d, effect_state *st, uint32_t w, uint32_t h,
                                  flux_format fmt, flux_image **out, output_entry **out_lease) {
    for (output_entry *o = st->outputs; o; o = o->next) {
        if (!o->leased && o->width == w && o->height == h && o->format == fmt) {
            o->leased = true;
            *out = o->image;
            *out_lease = o;
            return FLUX_OK;
        }
    }
    flux_image *img = nullptr;
    flux_result r = flux_image_create_compute_writable(d, w, h, fmt, &img);
    if (r != FLUX_OK)
        return r;

    output_entry *o = flux_internal_alloc(d, sizeof(*o));
    if (!o) {
        flux_image_release(img);
        return FLUX_ERROR_OUT_OF_MEMORY;
    }
    o->width = w;
    o->height = h;
    o->format = fmt;
    o->image = img;
    o->leased = true;
    o->next = st->outputs;
    st->outputs = o;
    *out = img;
    *out_lease = o;
    return FLUX_OK;
}

/* ------------------------------------------------------------------ */
/*  Pipeline build                                                    */
/* ------------------------------------------------------------------ */

static flux_result ensure_pipeline(flux_device *d, flux_compute_pipeline **slot,
                                   const unsigned char *spv, size_t spv_bytes,
                                   uint32_t push_bytes) {
    if (*slot)
        return FLUX_OK;
    flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
    pdesc.spirv = (const uint32_t *)spv;
    pdesc.spirv_word_count = spv_bytes / sizeof(uint32_t);
    pdesc.entry_point = "main";
    pdesc.push_constant_bytes = push_bytes;
    flux_result r = flux_compute_pipeline_create(d, &pdesc, slot);
    if (r != FLUX_OK)
        return r;
    /* The pipeline lives in per-device module state and is released
     * by effect_state_destroy inside flux_device_release; a strong
     * device ref would cycle and leak the whole device. */
    flux_compute_pipeline_make_device_weak(*slot);
    return FLUX_OK;
}

static flux_result ensure_blur_pipeline(flux_device *d, effect_state *st, bool is16f) {
    return ensure_pipeline(d, &st->blur_pipelines[is16f ? 1 : 0],
                           is16f ? effect_blur_16f_spv : effect_blur_spv,
                           is16f ? sizeof(effect_blur_16f_spv) : sizeof(effect_blur_spv),
                           sizeof(effect_blur_push));
}

static flux_result ensure_backdrop_pipeline(flux_device *d, effect_state *st, bool is16f) {
    return ensure_pipeline(d, &st->backdrop_pipelines[is16f ? 1 : 0],
                           is16f ? effect_backdrop_16f_spv : effect_backdrop_spv,
                           is16f ? sizeof(effect_backdrop_16f_spv) : sizeof(effect_backdrop_spv),
                           sizeof(effect_backdrop_push));
}

/* Storage/intermediate format for an effect input (ADR-0069): 8-bit
 * SDR content keeps the historic RGBA8 path; 16F working-space content
 * stays 16F so blurring runs in linear light — when the device
 * advertises rgba16f storage. */
static flux_result effect_resolve_storage(effect_state *st, const flux_image *in,
                                          flux_format *out, bool *out_16f) {
    if (in->format == FLUX_FORMAT_RGBA8_UNORM || in->format == FLUX_FORMAT_BGRA8_UNORM) {
        *out = FLUX_FORMAT_RGBA8_UNORM;
        *out_16f = false;
        return FLUX_OK;
    }
    if (in->format == FLUX_FORMAT_RGBA16_SFLOAT) {
        if (!st->storage_16f_supported) {
            FLUX_FAIL(FLUX_ERROR_UNSUPPORTED,
                      "16F effect input needs rgba16f storage support on this device");
            return FLUX_ERROR_UNSUPPORTED;
        }
        *out = FLUX_FORMAT_RGBA16_SFLOAT;
        *out_16f = true;
        return FLUX_OK;
    }
    FLUX_FAIL(FLUX_ERROR_UNSUPPORTED,
              "effect input format not supported (use RGBA8/BGRA8_UNORM or RGBA16_SFLOAT)");
    return FLUX_ERROR_UNSUPPORTED;
}

/* ------------------------------------------------------------------ */
/*  Barrier helpers                                                   */
/* ------------------------------------------------------------------ */

/* Emit a compute-write → compute-read barrier on `image`, no layout
 * transition (image stays in GENERAL). Used between the two passes
 * and after the final pass. */
static void barrier_compute_write_to_read(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask =
            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_READ_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* A reusable frame-slot image may have been sampled by the slot's previous
 * submission. begin_frame waited that slot's fence; this barrier expresses
 * the device-side read/write dependency before the next compute overwrite. */
static void barrier_reuse_to_compute_write(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask =
            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

static void barrier_compute_write_to_write(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 barrier = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo info = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &barrier,
    };
    vkCmdPipelineBarrier2(cmd, &info);
}

static flux_result record_blur_dispatch(effect_state *st, flux_device *d, VkCommandBuffer cmd,
                                        flux_image *in, flux_image *intermediate,
                                        flux_image *output, float requested_sigma, bool is16f) {
    float sigma = requested_sigma;
    if (!(sigma == sigma) || sigma < 0.0f)
        sigma = 0.0f;
    if (sigma > FLUX_EFFECT_BLUR_SIGMA_MAX)
        sigma = FLUX_EFFECT_BLUR_SIGMA_MAX;
    int32_t radius = (int32_t)ceilf(3.0f * sigma);
    if (radius > EFFECT_BLUR_RADIUS_MAX)
        radius = EFFECT_BLUR_RADIUS_MAX;

    barrier_reuse_to_compute_write(cmd, intermediate->image);
    barrier_reuse_to_compute_write(cmd, output->image);

    flux_bindless_handle sampler_h = flux_device_default_sampler_handle(d);
    effect_blur_push pc = {
        .in_handle = in->bindless,
        .sampler_handle = sampler_h,
        .out_handle = intermediate->bindless_storage,
        .width = in->width,
        .height = in->height,
        .radius = radius,
        .sigma = (sigma <= 0.0f) ? 1.0f : sigma,
        .axis = 0u,
    };
    uint32_t gx = (in->width + EFFECT_BLUR_WG - 1) / EFFECT_BLUR_WG;
    uint32_t gy = (in->height + EFFECT_BLUR_WG - 1) / EFFECT_BLUR_WG;
    flux_compute_dispatch(cmd, st->blur_pipelines[is16f ? 1 : 0], &pc, sizeof(pc), gx, gy, 1);

    barrier_compute_write_to_read(cmd, intermediate->image);

    pc.in_handle = intermediate->bindless;
    pc.out_handle = output->bindless_storage;
    pc.axis = 1u;
    flux_compute_dispatch(cmd, st->blur_pipelines[is16f ? 1 : 0], &pc, sizeof(pc), gx, gy, 1);

    barrier_compute_write_to_read(cmd, output->image);
    return FLUX_OK;
}

/* ------------------------------------------------------------------ */
/*  Public: flux_effect_blur                                          */
/* ------------------------------------------------------------------ */

flux_result flux_effect_blur(VkCommandBuffer cmd, const flux_effect_blur_desc *desc,
                             flux_image **out) {
    if (!cmd || !desc || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    if (desc->type != FLUX_TYPE_EFFECT_BLUR_DESC) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT, "desc->type != FLUX_TYPE_EFFECT_BLUR_DESC");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    if (desc->next) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT,
                  "exact blur does not accept reusable-blur extensions");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    if (!desc->input) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT, "blur input is null");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    flux_image *in = desc->input;
    flux_device *d = in->device;
    if (in->bindless == FLUX_BINDLESS_INVALID) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT, "blur input lacks sampled bindless handle");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    *out = nullptr;

    effect_state *st = effect_state_get_or_init(d);
    if (!st)
        return FLUX_ERROR_OUT_OF_MEMORY;

    /* 8-bit SDR content takes the historic RGBA8 path; 16F working-space
     * content stays 16F so the blur runs in linear light (ADR-0069). */
    flux_format storage_format;
    bool is16f;
    flux_result rr = effect_resolve_storage(st, in, &storage_format, &is16f);
    if (rr != FLUX_OK)
        return rr;

    flux_platform_mutex_lock(&st->lock);

    flux_result r = ensure_blur_pipeline(d, st, is16f);
    if (r != FLUX_OK) {
        flux_platform_mutex_unlock(&st->lock);
        return r;
    }

    flux_image *intermediate = nullptr;
    intermediate_entry *intermediate_lease = nullptr;
    r = acquire_intermediate(d, st, in->width, in->height, storage_format, &intermediate,
                             &intermediate_lease);
    if (r != FLUX_OK) {
        flux_platform_mutex_unlock(&st->lock);
        return r;
    }

    flux_image *output = nullptr;
    output_entry *output_lease = nullptr;
    r = acquire_output(d, st, in->width, in->height, storage_format, &output, &output_lease);
    if (r != FLUX_OK) {
        intermediate_lease->leased = false;
        flux_platform_mutex_unlock(&st->lock);
        return r;
    }
    (void)output_lease;

    flux_platform_mutex_unlock(&st->lock);

    r = record_blur_dispatch(st, d, cmd, in, intermediate, output, desc->sigma, is16f);
    if (r != FLUX_OK)
        return r;
    *out = output;
    return FLUX_OK;
}

/* ------------------------------------------------------------------ */
/*  Reusable frame-slot realtime blur                                 */
/* ------------------------------------------------------------------ */

flux_result flux_blur_filter_create(flux_device *device, flux_blur_filter **out) {
    if (!device || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out = nullptr;
    flux_blur_filter *filter = flux_internal_alloc(device, sizeof(*filter));
    if (!filter)
        return FLUX_ERROR_OUT_OF_MEMORY;
    atomic_init(&filter->ref_count, 1u);
    filter->device = flux_device_retain(device);
    *out = filter;
    return FLUX_OK;
}

flux_blur_filter *flux_blur_filter_retain(flux_blur_filter *filter) {
    if (filter)
        atomic_fetch_add_explicit(&filter->ref_count, 1u, memory_order_relaxed);
    return filter;
}

void flux_blur_filter_release(flux_blur_filter *filter) {
    if (!filter)
        return;
    if (atomic_fetch_sub_explicit(&filter->ref_count, 1u, memory_order_acq_rel) != 1u)
        return;
    flux_device *device = filter->device;
    for (uint32_t i = 0; i < FLUX_MAX_FRAMES_IN_FLIGHT; ++i) {
        if (filter->slots[i].output)
            flux_image_release(filter->slots[i].output);
        if (filter->slots[i].quarter)
            flux_image_release(filter->slots[i].quarter);
        if (filter->slots[i].half)
            flux_image_release(filter->slots[i].half);
    }
    flux_internal_free(device, filter);
    flux_device_release(device);
}

static flux_result blur_filter_ensure_slot(flux_blur_filter *filter, uint32_t index,
                                           const flux_image *input, flux_format storage_format) {
    blur_filter_slot *slot = &filter->slots[index];
    if (slot->half && slot->quarter && slot->output && slot->width == input->width &&
        slot->height == input->height && slot->format == storage_format)
        return FLUX_OK;

    if (slot->output)
        flux_image_release(slot->output);
    if (slot->quarter)
        flux_image_release(slot->quarter);
    if (slot->half)
        flux_image_release(slot->half);
    *slot = (blur_filter_slot){0};

    uint32_t half_width = (input->width + 1u) / 2u;
    uint32_t half_height = (input->height + 1u) / 2u;
    uint32_t quarter_width = (half_width + 1u) / 2u;
    uint32_t quarter_height = (half_height + 1u) / 2u;
    flux_result r = flux_image_create_compute_writable(filter->device, half_width, half_height,
                                                       storage_format, &slot->half);
    if (r != FLUX_OK)
        return r;
    r = flux_image_create_compute_writable(filter->device, quarter_width, quarter_height,
                                           storage_format, &slot->quarter);
    if (r != FLUX_OK)
        goto fail;
    r = flux_image_create_compute_writable(filter->device, input->width, input->height,
                                           storage_format, &slot->output);
    if (r != FLUX_OK)
        goto fail;
    slot->width = input->width;
    slot->height = input->height;
    slot->format = storage_format;
    return FLUX_OK;

fail:
    if (slot->quarter)
        flux_image_release(slot->quarter);
    if (slot->half)
        flux_image_release(slot->half);
    *slot = (blur_filter_slot){0};
    return r;
}

static bool map_effect_region(const flux_effect_region *region, uint32_t root_width,
                              uint32_t root_height, uint32_t output_width, uint32_t output_height,
                              uint32_t *out_x, uint32_t *out_y, uint32_t *out_width,
                              uint32_t *out_height) {
    uint64_t x0 = region->x < root_width ? region->x : root_width;
    uint64_t y0 = region->y < root_height ? region->y : root_height;
    uint64_t x1 = (uint64_t)region->x + region->width;
    uint64_t y1 = (uint64_t)region->y + region->height;
    if (x1 > root_width)
        x1 = root_width;
    if (y1 > root_height)
        y1 = root_height;
    if (x1 <= x0 || y1 <= y0)
        return false;

    /* Map outward so a fractional pyramid edge can never discard a source
     * pixel requested by the caller. */
    uint64_t ox0 = x0 * output_width / root_width;
    uint64_t oy0 = y0 * output_height / root_height;
    uint64_t ox1 = (x1 * output_width + root_width - 1u) / root_width;
    uint64_t oy1 = (y1 * output_height + root_height - 1u) / root_height;
    if (ox1 > output_width)
        ox1 = output_width;
    if (oy1 > output_height)
        oy1 = output_height;
    if (ox1 <= ox0 || oy1 <= oy0)
        return false;
    *out_x = (uint32_t)ox0;
    *out_y = (uint32_t)oy0;
    *out_width = (uint32_t)(ox1 - ox0);
    *out_height = (uint32_t)(oy1 - oy0);
    return true;
}

static void record_backdrop_pass(effect_state *st, flux_device *device, VkCommandBuffer cmd,
                                 flux_image *input, flux_image *output, float offset, uint32_t mode,
                                 uint32_t root_width, uint32_t root_height,
                                 const flux_effect_region *regions, uint32_t region_count,
                                 bool is16f) {
    barrier_reuse_to_compute_write(cmd, output->image);
    flux_compute_pipeline *pipeline = st->backdrop_pipelines[is16f ? 1 : 0];
    effect_backdrop_push pc = {
        .in_handle = input->bindless,
        .sampler_handle = flux_device_default_sampler_handle(device),
        .out_handle = output->bindless_storage,
        .input_width = input->width,
        .input_height = input->height,
        .output_width = output->width,
        .output_height = output->height,
        .offset = offset,
        .mode = mode,
    };
    if (!regions || region_count == 0) {
        pc.region_width = output->width;
        pc.region_height = output->height;
        uint32_t gx = (output->width + EFFECT_BLUR_WG - 1u) / EFFECT_BLUR_WG;
        uint32_t gy = (output->height + EFFECT_BLUR_WG - 1u) / EFFECT_BLUR_WG;
        flux_compute_dispatch(cmd, pipeline, &pc, sizeof(pc), gx, gy, 1u);
    } else {
        bool dispatched = false;
        for (uint32_t i = 0; i < region_count; ++i) {
            if (!map_effect_region(&regions[i], root_width, root_height, output->width,
                                   output->height, &pc.origin_x, &pc.origin_y, &pc.region_width,
                                   &pc.region_height))
                continue;
            if (dispatched)
                barrier_compute_write_to_write(cmd, output->image);
            uint32_t gx = (pc.region_width + EFFECT_BLUR_WG - 1u) / EFFECT_BLUR_WG;
            uint32_t gy = (pc.region_height + EFFECT_BLUR_WG - 1u) / EFFECT_BLUR_WG;
            flux_compute_dispatch(cmd, pipeline, &pc, sizeof(pc), gx, gy, 1u);
            dispatched = true;
        }
    }
    barrier_compute_write_to_read(cmd, output->image);
}

static void record_backdrop_filter(effect_state *st, flux_device *device, VkCommandBuffer cmd,
                                   flux_image *input, blur_filter_slot *slot, float requested_sigma,
                                   const flux_effect_region *regions, uint32_t region_count,
                                   bool is16f) {
    float sigma = requested_sigma;
    if (!(sigma == sigma) || sigma < 0.0f)
        sigma = 0.0f;
    if (sigma > FLUX_EFFECT_BLUR_SIGMA_MAX)
        sigma = FLUX_EFFECT_BLUR_SIGMA_MAX;

    if (sigma == 0.0f) {
        record_backdrop_pass(st, device, cmd, input, slot->output, 0.0f, 2u, input->width,
                             input->height, regions, region_count, is16f);
        return;
    }

    /* Two pyramid levels provide a wide UI blur with fixed work. Sigma tunes
     * the sub-texel offsets rather than growing a per-pixel kernel loop. */
    float offset = fminf(fmaxf(sigma * 0.25f, 0.5f), 2.5f);
    record_backdrop_pass(st, device, cmd, input, slot->half, offset, 0u, input->width,
                         input->height, regions, region_count, is16f);
    record_backdrop_pass(st, device, cmd, slot->half, slot->quarter, offset, 0u, input->width,
                         input->height, regions, region_count, is16f);
    record_backdrop_pass(st, device, cmd, slot->quarter, slot->half, offset, 1u, input->width,
                         input->height, regions, region_count, is16f);
    record_backdrop_pass(st, device, cmd, slot->half, slot->output, offset, 1u, input->width,
                         input->height, regions, region_count, is16f);
}

flux_result flux_blur_filter_apply(flux_blur_filter *filter, flux_frame *frame,
                                   const flux_effect_blur_desc *desc, flux_image **out) {
    if (!filter || !frame || !desc || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out = nullptr;
    if (desc->type != FLUX_TYPE_EFFECT_BLUR_DESC || !desc->input) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT, "invalid reusable blur descriptor");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    const flux_effect_blur_regions_desc *region_desc = desc->next;
    if (region_desc &&
        (region_desc->type != FLUX_TYPE_EFFECT_BLUR_REGIONS_DESC || region_desc->next ||
         (region_desc->region_count > 0 && !region_desc->regions))) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT, "invalid reusable blur regions extension");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    if (!frame->surface || frame->state != FLUX_FRAME_STATE_RECORDING || frame->pass_active) {
        FLUX_FAIL(FLUX_ERROR_INVALID_STATE,
                  "reusable blur requires a recording frame pass boundary");
        return FLUX_ERROR_INVALID_STATE;
    }
    flux_image *input = desc->input;
    if (frame->surface->device != filter->device || input->device != filter->device) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT,
                  "blur filter, frame, and input use different devices");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    if (input->bindless == FLUX_BINDLESS_INVALID) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT, "reusable blur input lacks a sampled handle");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    effect_state *st = effect_state_get_or_init(filter->device);
    if (!st)
        return FLUX_ERROR_OUT_OF_MEMORY;
    /* 8-bit SDR content takes the historic RGBA8 path; 16F working-space
     * content stays 16F so the pyramid runs in linear light (ADR-0069). */
    flux_format storage_format;
    bool is16f;
    flux_result rr = effect_resolve_storage(st, input, &storage_format, &is16f);
    if (rr != FLUX_OK)
        return rr;
    const flux_effect_region *regions = region_desc ? region_desc->regions : nullptr;
    uint32_t region_count = region_desc ? region_desc->region_count : 0u;
    if (region_count > 0) {
        bool any_valid = false;
        for (uint32_t i = 0; i < region_count; ++i) {
            uint32_t x, y, width, height;
            if (map_effect_region(&regions[i], input->width, input->height, input->width,
                                  input->height, &x, &y, &width, &height)) {
                any_valid = true;
                break;
            }
        }
        if (!any_valid) {
            FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT,
                      "reusable blur region list has no pixels inside the input");
            return FLUX_ERROR_INVALID_ARGUMENT;
        }
    }
    uint32_t index = flux_frame_index(frame);
    if (index >= FLUX_MAX_FRAMES_IN_FLIGHT)
        return FLUX_ERROR_OUT_OF_RANGE;

    flux_result r = blur_filter_ensure_slot(filter, index, input, storage_format);
    if (r != FLUX_OK)
        return r;

    flux_platform_mutex_lock(&st->lock);
    r = ensure_backdrop_pipeline(filter->device, st, is16f);
    flux_platform_mutex_unlock(&st->lock);
    if (r != FLUX_OK)
        return r;

    blur_filter_slot *slot = &filter->slots[index];
    record_backdrop_filter(st, filter->device, flux_frame_vk_command_buffer(frame), input, slot,
                           desc->sigma, regions, region_count, is16f);
    *out = slot->output;
    return FLUX_OK;
}

/* ------------------------------------------------------------------ */
/*  Public: flux_effect_promote                                       */
/* ------------------------------------------------------------------ */

static flux_result promote_copy_submit(flux_device *d, VkImage src_image, VkImage dst_image,
                                       uint32_t width, uint32_t height) {
    VkCommandPool pool = VK_NULL_HANDLE;
    VkCommandBuffer cmd = VK_NULL_HANDLE;
    VkResult vr = flux_vk_new_transient_cmd(d, d->graphics_family, &pool, &cmd);
    if (vr != VK_SUCCESS) {
        FLUX_FAIL_VK(FLUX_ERROR_BACKEND_FAILURE, "promote command buffer allocation failed", vr);
        return FLUX_ERROR_BACKEND_FAILURE;
    }

    VkImageSubresourceRange subres = {
        .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
        .levelCount = 1,
        .layerCount = 1,
    };

    VkImageMemoryBarrier2 pre[2] = {
        /* src: GENERAL → TRANSFER_SRC */
        {
            .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
            .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
            .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
            .dstStageMask = VK_PIPELINE_STAGE_2_COPY_BIT,
            .dstAccessMask = VK_ACCESS_2_TRANSFER_READ_BIT,
            .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
            .newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
            .image = src_image,
            .subresourceRange = subres,
        },
        /* dst: SHADER_READ_ONLY (flux_image_create's terminal layout) → TRANSFER_DST */
        {
            .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
            .srcStageMask = VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT,
            .srcAccessMask = 0,
            .dstStageMask = VK_PIPELINE_STAGE_2_COPY_BIT,
            .dstAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT,
            .oldLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
            .newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
            .image = dst_image,
            .subresourceRange = subres,
        },
    };
    VkDependencyInfo pre_di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 2,
        .pImageMemoryBarriers = pre,
    };
    vkCmdPipelineBarrier2(cmd, &pre_di);

    VkImageCopy region = {
        .srcSubresource = {.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT, .layerCount = 1},
        .dstSubresource = {.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT, .layerCount = 1},
        .extent = {width, height, 1},
    };
    vkCmdCopyImage(cmd, src_image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, dst_image,
                   VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

    VkImageMemoryBarrier2 post[2] = {
        /* src: TRANSFER_SRC → GENERAL (restore for future effect re-use) */
        {
            .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
            .srcStageMask = VK_PIPELINE_STAGE_2_COPY_BIT,
            .srcAccessMask = VK_ACCESS_2_TRANSFER_READ_BIT,
            .dstStageMask = VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT,
            .dstAccessMask = 0,
            .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
            .newLayout = VK_IMAGE_LAYOUT_GENERAL,
            .image = src_image,
            .subresourceRange = subres,
        },
        /* dst: TRANSFER_DST → SHADER_READ_ONLY (caller will sample it) */
        {
            .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
            .srcStageMask = VK_PIPELINE_STAGE_2_COPY_BIT,
            .srcAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT,
            .dstStageMask =
                VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
            .dstAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT,
            .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
            .newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
            .image = dst_image,
            .subresourceRange = subres,
        },
    };
    VkDependencyInfo post_di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 2,
        .pImageMemoryBarriers = post,
    };
    vkCmdPipelineBarrier2(cmd, &post_di);

    vr = vkEndCommandBuffer(cmd);
    if (vr == VK_SUCCESS)
        vr = flux_vk_submit_one_shot_and_wait(d, cmd);
    vkDestroyCommandPool(d->device, pool, nullptr);

    if (vr != VK_SUCCESS) {
        flux_result r = vr == VK_TIMEOUT             ? FLUX_ERROR_TIMEOUT
                        : vr == VK_ERROR_DEVICE_LOST ? FLUX_ERROR_DEVICE_LOST
                                                     : FLUX_ERROR_BACKEND_FAILURE;
        FLUX_FAIL_VK(r, "promote copy submit failed", vr);
        return r;
    }
    return FLUX_OK;
}

flux_result flux_effect_promote(flux_image *transient, flux_image **out) {
    if (!transient || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    if (transient->bindless_storage == FLUX_BINDLESS_INVALID) {
        FLUX_FAIL(FLUX_ERROR_INVALID_ARGUMENT,
                  "flux_effect_promote source is not an effect output (no storage handle)");
        return FLUX_ERROR_INVALID_ARGUMENT;
    }
    *out = nullptr;

    flux_device *d = transient->device;
    flux_image_desc ddesc = FLUX_IMAGE_DESC_INIT;
    ddesc.width = transient->width;
    ddesc.height = transient->height;
    ddesc.format = transient->format;
    flux_image *dst = nullptr;
    flux_result r = flux_image_create(d, &ddesc, &dst);
    if (r != FLUX_OK)
        return r;

    r = promote_copy_submit(d, transient->image, dst->image, transient->width, transient->height);
    if (r != FLUX_OK) {
        flux_image_release(dst);
        return r;
    }
    *out = dst;
    return FLUX_OK;
}

/* ------------------------------------------------------------------ */
/*  Public: flux_effect_reset                                         */
/* ------------------------------------------------------------------ */

void flux_effect_reset(flux_device *d) {
    if (!d)
        return;
    flux_platform_mutex_lock(&d->module_state_lock);
    effect_state *st = d->effect_state;
    flux_platform_mutex_unlock(&d->module_state_lock);
    if (!st)
        return;
    flux_platform_mutex_lock(&st->lock);
    for (output_entry *o = st->outputs; o; o = o->next)
        o->leased = false;
    for (intermediate_entry *e = st->intermediates; e; e = e->next)
        e->leased = false;
    flux_platform_mutex_unlock(&st->lock);
}
