/*
 * julia_morph — a Julia set morphed by compute, presented via canvas.
 *
 * Mathematical showcase: every pixel iterates z = z² + c with z seeded at
 * the pixel's complex coordinate while the host slides c around the circle
 * |c| = 0.7885 (angle = t·0.1). Crossing the Mandelbrot boundary morphs
 * the set between connected blobs, dendrites and Cantor dust; smooth
 * (fractional) escape-time counts feed a slowly drifting cosine palette.
 *
 * It is also the compute counterpart of the visual showcases — the first
 * example to show the compute → storage image → present path
 * (examples/flux/compute_fill.c only reads an SSBO back to the CPU):
 *   1. DISPATCH — a compute pipeline writes the escape-time colours into
 *      a storage image through the device bindless heap (GENERAL layout,
 *      slot handle passed in push constants).
 *   2. COPY     — vkCmdCopyImage moves the result into a public flux_image
 *      (SHADER_READ_ONLY), because flux has no public storage-image
 *      constructor (the internal compute-writable one is effect-only).
 *   3. BLIT     — flux_canvas_draw_image puts that image on the surface.
 *
 * Key flux APIs:  flux_compute_pipeline_create, flux_compute_dispatch,
 *                 flux_bindless_register_storage_image,
 *                 flux_canvas_begin, flux_canvas_draw_image, flux_canvas_end
 * Plumbing (raw Vulkan, not flux): GLFW window + VkSurfaceKHR creation,
 *   the storage image/memory/view, the per-frame layout barriers and copy.
 * Requires -Dcompute=true (and the canvas module, on by default).
 */
#include <flux/canvas.h>
#include <flux/compute.h>
#include <flux/flux.h>
#include <flux/vulkan.h>

#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>

#include "pipeline_cache.h"

#include <math.h>
#include <stdalign.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* SPIR-V — uint32_t-aligned so Vulkan can read it as code words.
 * C23 #embed primarily; toolchains without it (MSVC cl, Apple Clang)
 * include the spv2h.py-generated header instead (same array).
 * FLUX_SHADER_NO_EMBED forces the fallback for testing. */
#if defined(__has_embed) && !defined(FLUX_SHADER_NO_EMBED)
#if __has_embed("julia_morph.comp.spv")
#define EXAMPLE_SHADERS_EMBED 1
#endif
#endif

#ifdef EXAMPLE_SHADERS_EMBED
alignas(uint32_t) static const unsigned char julia_morph_comp_spv[] = {
#embed "julia_morph.comp.spv"
};
#else
#include "julia_morph_comp_spv.h" /* generated by tools/spv2h.py; same array */
#endif

#define WORKGROUP 16u /* matches local_size_x/y in julia_morph.comp */

/* Must match the push-constant block in julia_morph.comp: flat 4-byte
 * scalars only, so the C and std430 layouts coincide. */
typedef struct julia_push {
    uint32_t out_handle; /* storage image bindless slot */
    uint32_t width;      /* output extent in pixels     */
    uint32_t height;
    float c_re;          /* Julia constant, animated    */
    float c_im;
    float time;          /* seconds; palette phase      */
} julia_push;
static_assert(sizeof(julia_push) == 24, "julia_push must match the GLSL push block");

/* ------------------------------------------------------------------ */
/*  Compute target                                                    */
/* ------------------------------------------------------------------ */

/* A raw storage image the compute shader writes, plus the public
 * flux_image the canvas samples. The storage image stays in
 * VK_IMAGE_LAYOUT_GENERAL for its whole life — flux's own
 * compute-writable images make the same trade (see image.c in the
 * canvas module): no per-frame layout transitions on the compute image,
 * at the cost of the sampling-side optimisations GENERAL gives up. */
typedef struct storage_target {
    VkImage image;               /* STORAGE | TRANSFER_SRC            */
    VkDeviceMemory memory;
    VkImageView view;
    flux_bindless_handle handle; /* bindless storage slot             */
    flux_image *present;         /* SAMPLED | TRANSFER_DST copy dest  */
    uint32_t width;
    uint32_t height;
    bool first_use;              /* image still in UNDEFINED layout   */
} storage_target;

static uint32_t find_mt(flux_device *d, uint32_t filter, VkMemoryPropertyFlags want) {
    VkPhysicalDeviceMemoryProperties mp;
    vkGetPhysicalDeviceMemoryProperties(flux_device_vk_physical_device(d), &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; ++i) {
        if (!(filter & (1u << i)))
            continue;
        if ((mp.memoryTypes[i].propertyFlags & want) == want)
            return i;
    }
    return UINT32_MAX;
}

/* Call only with the GPU idle (creation is followed by wait_idle-free
 * first use; destruction here is immediate, not retire-queue deferred). */
static void target_destroy(flux_device *device, storage_target *t) {
    VkDevice vk = flux_device_vk_device(device);
    if (t->handle != FLUX_BINDLESS_INVALID)
        flux_bindless_release(device, t->handle);
    if (t->present)
        flux_image_release(t->present);
    if (t->view)
        vkDestroyImageView(vk, t->view, nullptr);
    if (t->image)
        vkDestroyImage(vk, t->image, nullptr);
    if (t->memory)
        vkFreeMemory(vk, t->memory, nullptr);
    *t = (storage_target){.handle = FLUX_BINDLESS_INVALID};
}

static bool target_create(flux_device *device, storage_target *t, uint32_t w, uint32_t h) {
    VkDevice vk = flux_device_vk_device(device);
    *t = (storage_target){.handle = FLUX_BINDLESS_INVALID};

    VkImageCreateInfo ici = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
        .imageType = VK_IMAGE_TYPE_2D,
        .format = VK_FORMAT_R8G8B8A8_UNORM,
        .extent = {w, h, 1},
        .mipLevels = 1,
        .arrayLayers = 1,
        .samples = VK_SAMPLE_COUNT_1_BIT,
        .tiling = VK_IMAGE_TILING_OPTIMAL,
        .usage = VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT,
        .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
    };
    if (vkCreateImage(vk, &ici, nullptr, &t->image) != VK_SUCCESS)
        goto fail;

    VkMemoryRequirements mr;
    vkGetImageMemoryRequirements(vk, t->image, &mr);
    uint32_t mt = find_mt(device, mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (mt == UINT32_MAX)
        goto fail;
    VkMemoryAllocateInfo mai = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
        .allocationSize = mr.size,
        .memoryTypeIndex = mt,
    };
    if (vkAllocateMemory(vk, &mai, nullptr, &t->memory) != VK_SUCCESS)
        goto fail;
    vkBindImageMemory(vk, t->image, t->memory, 0);

    VkImageViewCreateInfo ivci = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
        .image = t->image,
        .viewType = VK_IMAGE_VIEW_TYPE_2D,
        .format = VK_FORMAT_R8G8B8A8_UNORM,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    if (vkCreateImageView(vk, &ivci, nullptr, &t->view) != VK_SUCCESS)
        goto fail;

    /* The descriptor just records the layout shaders will find the image
     * in; the first per-frame barrier moves UNDEFINED -> GENERAL before
     * any dispatch touches it. */
    if (flux_bindless_register_storage_image(device, t->view, VK_IMAGE_LAYOUT_GENERAL,
                                             &t->handle) != FLUX_OK)
        goto fail;

    /* Copy destination the canvas can sample. Created empty, so flux
     * leaves it in SHADER_READ_ONLY_OPTIMAL — the steady-state layout
     * the per-frame barriers assume. */
    flux_image_desc idesc = FLUX_IMAGE_DESC_INIT;
    idesc.width = w;
    idesc.height = h;
    idesc.format = FLUX_FORMAT_RGBA8_UNORM;
    if (flux_image_create(device, &idesc, &t->present) != FLUX_OK)
        goto fail;

    t->width = w;
    t->height = h;
    t->first_use = true;
    return true;

fail:
    target_destroy(device, t);
    return false;
}

/* (Re)create the target when the surface extent changes. The outgoing
 * image may still be read by submitted frames, so drain the device
 * before destroying it — resize is rare, and the retire queue only
 * defers flux-owned images, not this example's raw VkImage. */
static bool target_ensure(flux_device *device, storage_target *t, uint32_t w, uint32_t h) {
    if (t->image && t->width == w && t->height == h)
        return true;
    flux_device_wait_idle(device);
    target_destroy(device, t);
    return target_create(device, t, w, h);
}

/* One image barrier, both the layout-transition and the pure ordering
 * (GENERAL -> GENERAL) kind. Stage/access pairs at the call sites follow
 * the flux effect module's compute->transfer and transfer->sample
 * idioms. */
static void record_image_barrier(VkCommandBuffer cmd, VkImage image,
                                 VkPipelineStageFlags2 src_stage, VkAccessFlags2 src_access,
                                 VkPipelineStageFlags2 dst_stage, VkAccessFlags2 dst_access,
                                 VkImageLayout old_layout, VkImageLayout new_layout) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = src_stage,
        .srcAccessMask = src_access,
        .dstStageMask = dst_stage,
        .dstAccessMask = dst_access,
        .oldLayout = old_layout,
        .newLayout = new_layout,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* ------------------------------------------------------------------ */
/*  Window                                                            */
/* ------------------------------------------------------------------ */

static void on_resize(GLFWwindow *win, int w, int h) {
    flux_surface *surface = glfwGetWindowUserPointer(win);
    if (surface && w > 0 && h > 0)
        (void)flux_surface_resize(surface, (uint32_t)w, (uint32_t)h);
}

int main(void) {
    int major, minor, patch;
    flux_version(&major, &minor, &patch);
    printf("flux %d.%d.%d (%s)\n", major, minor, patch, flux_version_string());

    if (!glfwInit()) {
        fprintf(stderr, "glfwInit failed\n");
        return 1;
    }
    if (!glfwVulkanSupported()) {
        fprintf(stderr, "no Vulkan via GLFW\n");
        glfwTerminate();
        return 1;
    }

    glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
    glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
    GLFWwindow *win = glfwCreateWindow(960, 540, "flux julia morph", nullptr, nullptr);
    if (!win) {
        glfwTerminate();
        return 1;
    }

    uint32_t ext_count = 0;
    const char **req_exts = glfwGetRequiredInstanceExtensions(&ext_count);
    const char *device_exts[] = {VK_KHR_SWAPCHAIN_EXTENSION_NAME};

    /* Pipeline-cache persistence is consumer-owned (Skia PersistentCache
     * model): flux never touches the filesystem. The example resolves a
     * path itself and wires load/save callbacks into the device desc. */
    flux_pipeline_cache_file cache = FLUX_PIPELINE_CACHE_FILE_INIT;
    flux_pipeline_cache_file_set_default_path(&cache, "julia_morph.bin");

    /* One frame in flight: the single compute target is re-written every
     * frame, so the frame fence must serialise its reuse (the same
     * choice liquid_glass makes). That is what lets the per-frame
     * barriers below use simple TOP_OF_PIPE sources for cross-frame
     * hazards. */
    flux_device_desc ddesc = {
        .type = FLUX_TYPE_DEVICE_DESC,
        .log = flux_console_logger,
        .validation = FLUX_VALIDATION_AUTO,
        .required_instance_extensions = req_exts,
        .required_instance_extension_count = ext_count,
        .required_device_extensions = device_exts,
        .required_device_extension_count = sizeof(device_exts) / sizeof(*device_exts),
        .frames_in_flight = 1,
        .pipeline_cache_load = flux_pipeline_cache_file_load,
        .pipeline_cache_save = flux_pipeline_cache_file_save,
        .pipeline_cache_userdata = &cache,
    };
    flux_device *device = nullptr;
    flux_result r = flux_device_create(&ddesc, &device);
    if (r != FLUX_OK) {
        flux_error_info ei;
        flux_get_last_error(&ei);
        fprintf(stderr, "flux_device_create -> %s\n  %s\n", flux_result_string(r),
                ei.message ? ei.message : "(no info)");
        glfwDestroyWindow(win);
        glfwTerminate();
        return (int)r;
    }

    VkSurfaceKHR vk_surface = VK_NULL_HANDLE;
    if (glfwCreateWindowSurface(flux_device_vk_instance(device), win, nullptr, &vk_surface) !=
        VK_SUCCESS) {
        fprintf(stderr, "glfwCreateWindowSurface failed\n");
        flux_device_release(device);
        glfwDestroyWindow(win);
        glfwTerminate();
        return 1;
    }

    int fbw = 0, fbh = 0;
    glfwGetFramebufferSize(win, &fbw, &fbh);
    flux_surface_desc sdesc = {
        .type = FLUX_TYPE_SURFACE_DESC,
        .vk_surface_khr = vk_surface,
        .width = (uint32_t)fbw,
        .height = (uint32_t)fbh,
        .vsync = true,
    };
    flux_surface *surface = nullptr;
    r = flux_surface_create(device, &sdesc, &surface);
    if (r != FLUX_OK) {
        flux_error_info ei;
        flux_get_last_error(&ei);
        fprintf(stderr, "flux_surface_create -> %s\n  %s\n", flux_result_string(r),
                ei.message ? ei.message : "(no info)");
        vkDestroySurfaceKHR(flux_device_vk_instance(device), vk_surface, nullptr);
        flux_device_release(device);
        glfwDestroyWindow(win);
        glfwTerminate();
        return (int)r;
    }
    glfwSetWindowUserPointer(win, surface);
    glfwSetFramebufferSizeCallback(win, on_resize);

    /* ===== end shared bootstrap (window + device + surface) =====
     * Everything below is what this example is actually about: a compute
     * pipeline writing a storage image, copied into a canvas-drawable
     * flux_image each frame. */
    flux_canvas_desc cdesc = {
        .type = FLUX_TYPE_CANVAS_DESC,
        .surface = surface,
    };
    flux_canvas *canvas = nullptr;
    r = flux_canvas_create(&cdesc, &canvas);
    if (r != FLUX_OK) {
        flux_error_info ei;
        flux_get_last_error(&ei);
        fprintf(stderr, "flux_canvas_create -> %s\n  %s\n", flux_result_string(r),
                ei.message ? ei.message : "(no info)");
        flux_surface_release(surface);
        vkDestroySurfaceKHR(flux_device_vk_instance(device), vk_surface, nullptr);
        flux_device_release(device);
        glfwDestroyWindow(win);
        glfwTerminate();
        return (int)r;
    }

    flux_compute_pipeline_desc pdesc = {
        .type = FLUX_TYPE_COMPUTE_PIPELINE_DESC,
        .spirv = (const uint32_t *)julia_morph_comp_spv,
        .spirv_word_count = sizeof(julia_morph_comp_spv) / sizeof(uint32_t),
        .entry_point = "main",
        .push_constant_bytes = sizeof(julia_push),
    };
    flux_compute_pipeline *pipe = nullptr;
    r = flux_compute_pipeline_create(device, &pdesc, &pipe);
    if (r != FLUX_OK) {
        flux_error_info ei;
        flux_get_last_error(&ei);
        fprintf(stderr, "flux_compute_pipeline_create -> %s\n  %s\n", flux_result_string(r),
                ei.message ? ei.message : "(no info)");
        flux_canvas_destroy(canvas);
        flux_surface_release(surface);
        vkDestroySurfaceKHR(flux_device_vk_instance(device), vk_surface, nullptr);
        flux_device_release(device);
        glfwDestroyWindow(win);
        glfwTerminate();
        return (int)r;
    }
    printf("compute pipeline ready (%zu SPIR-V bytes embedded)\n", sizeof(julia_morph_comp_spv));

    storage_target target = {.handle = FLUX_BINDLESS_INVALID};
    double start_time = glfwGetTime();
    int frame_no = 0;
    while (!glfwWindowShouldClose(win)) {
        glfwPollEvents();

        /* Resize, before any frame is open: the surface tracks the
         * window (see on_resize), the storage target tracks the surface. */
        flux_surface_info info;
        flux_surface_get_info(surface, &info);
        if (info.width == 0 || info.height == 0)
            continue; /* minimized */
        if (!target_ensure(device, &target, info.width, info.height)) {
            fprintf(stderr, "storage target create failed (%ux%u)\n", info.width, info.height);
            break;
        }

        flux_frame *frame = nullptr;
        r = flux_surface_begin_frame(surface, nullptr, &frame);
        if (r == FLUX_ERROR_SURFACE_LOST) {
            int w, h;
            glfwGetFramebufferSize(win, &w, &h);
            if (w > 0 && h > 0)
                (void)flux_surface_resize(surface, (uint32_t)w, (uint32_t)h);
            continue;
        }
        if (r == FLUX_ERROR_INVALID_STATE)
            continue;
        if (r != FLUX_OK) {
            fprintf(stderr, "begin_frame -> %s\n", flux_result_string(r));
            break;
        }

        VkCommandBuffer cmd = flux_frame_vk_command_buffer(frame);

        /* 1 — last frame's copy read (or creation) -> this write. */
        record_image_barrier(cmd, target.image,
                             target.first_use ? VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT
                                              : VK_PIPELINE_STAGE_2_COPY_BIT,
                             target.first_use ? 0 : VK_ACCESS_2_TRANSFER_READ_BIT,
                             VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
                             VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
                             target.first_use ? VK_IMAGE_LAYOUT_UNDEFINED
                                              : VK_IMAGE_LAYOUT_GENERAL,
                             VK_IMAGE_LAYOUT_GENERAL);
        target.first_use = false;

        float time = (float)(glfwGetTime() - start_time);
        float orbit = time * 0.1f;
        julia_push pc = {
            .out_handle = target.handle,
            .width = info.width,
            .height = info.height,
            .c_re = 0.7885f * cosf(orbit),
            .c_im = 0.7885f * sinf(orbit),
            .time = time,
        };
        flux_compute_dispatch(cmd, pipe, &pc, sizeof(pc),
                              (info.width + WORKGROUP - 1u) / WORKGROUP,
                              (info.height + WORKGROUP - 1u) / WORKGROUP, 1u);

        /* 2 — compute write -> copy read (image stays in GENERAL). */
        record_image_barrier(cmd, target.image, VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
                             VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT, VK_PIPELINE_STAGE_2_COPY_BIT,
                             VK_ACCESS_2_TRANSFER_READ_BIT, VK_IMAGE_LAYOUT_GENERAL,
                             VK_IMAGE_LAYOUT_GENERAL);

        /* 3 — the flux_image becomes the copy destination. Last frame's
         * sampling of it finished with the frame fence (one frame in
         * flight), so TOP_OF_PIPE suffices. */
        record_image_barrier(cmd, flux_image_vk_image(target.present),
                             VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT, 0, VK_PIPELINE_STAGE_2_COPY_BIT,
                             VK_ACCESS_2_TRANSFER_WRITE_BIT,
                             VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                             VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);

        VkImageCopy region = {
            .srcSubresource = {.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT, .layerCount = 1},
            .dstSubresource = {.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT, .layerCount = 1},
            .extent = {info.width, info.height, 1},
        };
        vkCmdCopyImage(cmd, target.image, VK_IMAGE_LAYOUT_GENERAL,
                       flux_image_vk_image(target.present), VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                       1, &region);

        /* 4 — copy write -> canvas sample below. */
        record_image_barrier(cmd, flux_image_vk_image(target.present),
                             VK_PIPELINE_STAGE_2_COPY_BIT, VK_ACCESS_2_TRANSFER_WRITE_BIT,
                             VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
                             VK_ACCESS_2_SHADER_SAMPLED_READ_BIT,
                             VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                             VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);

        flux_color clear = flux_color_rgba(0, 0, 0, 255);
        r = flux_canvas_begin(canvas, frame, &clear);
        if (r != FLUX_OK) {
            fprintf(stderr, "canvas_begin -> %s\n", flux_result_string(r));
            break;
        }
        flux_canvas_draw_image(canvas, target.present,
                               (flux_rect){0.0f, 0.0f, (float)info.width, (float)info.height},
                               nullptr);
        flux_canvas_end(canvas);

        r = flux_frame_submit(frame);
        if (r != FLUX_OK) {
            fprintf(stderr, "submit -> %s\n", flux_result_string(r));
            break;
        }
        r = flux_frame_present(frame);
        if (r == FLUX_ERROR_SURFACE_LOST) {
            int w, h;
            glfwGetFramebufferSize(win, &w, &h);
            if (w > 0 && h > 0)
                (void)flux_surface_resize(surface, (uint32_t)w, (uint32_t)h);
        } else if (r != FLUX_OK) {
            fprintf(stderr, "present -> %s\n", flux_result_string(r));
            break;
        }

        if (++frame_no == 1)
            printf("first julia frame presented (extent %ux%u)\n", info.width, info.height);
    }

    flux_device_wait_idle(device);
    target_destroy(device, &target);
    flux_compute_pipeline_release(pipe);
    flux_canvas_destroy(canvas);
    flux_surface_release(surface);
    vkDestroySurfaceKHR(flux_device_vk_instance(device), vk_surface, nullptr);
    flux_device_release(device);
    glfwDestroyWindow(win);
    glfwTerminate();
    return 0;
}
