/*
 * Analytic liquid-glass material — the convex-lens model of ADR-0046 with
 * the focus field of ADR-0050.
 *
 * prism is a separate library from flux: this file is implemented entirely
 * on flux's public API (compute pipelines, compute-writable images,
 * frame-slot queries, the bindless heap, raw Vulkan handle accessors).
 * flux owns the effect runtime; the material — its shader, the regions
 * policy below, and this dispatch machinery — lives here (ADR-0063).
 *
 * Layout:
 *   - shader bytecode (#embed or generated headers, same idiom as flux)
 *   - push-constant blocks matching the shaders
 *   - barrier helpers (raw Vulkan over flux_image_vk_image)
 *   - the frame-slot filter: per-slot output, footprint clearing, dispatch
 */

#include <prism/liquid_glass.h>

#include <flux/compute.h>
#include <flux/vulkan.h>

#include "regions.h"

#include <math.h>
#include <stdalign.h>
#include <stdatomic.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

/* Shader bytecode: C23 #embed, or generated headers (tools/spv2h.py)
 * where the compiler lacks it — same idiom as flux's renderer. */
#if defined(__has_embed) && !defined(PRISM_SHADER_NO_EMBED)
#if __has_embed("liquid_glass.comp.spv") && __has_embed("storage_clear.comp.spv")
#define PRISM_SHADERS_EMBED 1
#endif
#endif

#ifdef PRISM_SHADERS_EMBED
alignas(uint32_t) static const unsigned char liquid_glass_spv[] = {
#embed "liquid_glass.comp.spv"
};

alignas(uint32_t) static const unsigned char storage_clear_spv[] = {
#embed "storage_clear.comp.spv"
};
#else
#include "liquid_glass_spv.h"
#include "storage_clear_spv.h" /* generated by tools/spv2h.py; same arrays */
#endif

/* Push-constant block — must match liquid_glass.comp exactly. */
typedef struct liquid_glass_push {
    uint32_t input_handle;
    uint32_t blurred_handle;
    uint32_t sampler_handle;
    uint32_t output_handle;
    uint32_t width;
    uint32_t height;
    uint32_t origin_x;
    uint32_t origin_y;
    float shape0[4];
    float shape1[4];
    float radius0;
    float radius1;
    float blend_radius;
    float opacity;
    float refraction;
    float chromatic_aberration;
    float saturation;
    float brightness;
    float edge_width;
    float rim_light;
    float light_x;
    float light_y;
    uint32_t group_width;
    uint32_t group_height;
    uint32_t shape_count;
    float shadow_alpha;
    float shadow_blur;
    float shadow_offset_y;
    float size_reference;
    float size_scale_min;
    float tint_strength;
    float frost_strength;
    uint32_t tint_color;
    float focus_strength;
} liquid_glass_push;

/* Push-constant block — must match storage_clear.comp exactly. */
typedef struct storage_clear_push {
    uint32_t output_handle;
    uint32_t width;
    uint32_t height;
    uint32_t origin_x;
    uint32_t origin_y;
    uint32_t region_width;
    uint32_t region_height;
} storage_clear_push;

/* flux requires every device to accept 160 push-constant bytes, so the
 * material can rely on that budget on any flux device. */
static_assert(sizeof(liquid_glass_push) == 160,
              "liquid_glass_push no longer matches its shader block");
static_assert(sizeof(storage_clear_push) == 28,
              "storage_clear_push no longer matches its shader block");

#define PRISM_WG 16u
#define PRISM_STORAGE_FORMAT FLUX_FORMAT_RGBA8_UNORM

typedef struct liquid_glass_filter_slot {
    uint32_t width;
    uint32_t height;
    flux_image *output;
    bool initialized;
    uint32_t previous_count;
    liquid_glass_region previous[LIQUID_GLASS_MAX_GROUPS];
} liquid_glass_filter_slot;

struct prism_liquid_glass_filter {
    atomic_uint ref_count;
    flux_device *device; /* retained; slot images hold weak device refs */
    flux_compute_pipeline *glass_pipeline; /* lazily built on first apply */
    flux_compute_pipeline *clear_pipeline;
    liquid_glass_filter_slot slots[FLUX_MAX_FRAMES_IN_FLIGHT];
};

/* ------------------------------------------------------------------ */
/*  Barrier helpers (raw Vulkan over flux_image_vk_image)             */
/* ------------------------------------------------------------------ */

/* Emit a compute-write → compute-read barrier on `image`, no layout
 * transition (image stays in GENERAL). Makes the output sampleable by any
 * later shader stage. */
static void barrier_compute_write_to_read(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask =
            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_READ_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* A reusable frame-slot image may have been sampled by the slot's previous
 * submission. begin_frame waited that slot's fence; this barrier expresses
 * the device-side read/write dependency before the next compute overwrite. */
static void barrier_reuse_to_compute_write(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask =
            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* Groups source-over the persistent storage image. Make an earlier group's
 * write visible to both imageLoad and imageStore in the next group; a
 * write-only dependency lets a later shadow replace the body below it
 * instead of compositing over it. */
static void barrier_compute_write_to_read_write(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 barrier = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo info = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &barrier,
    };
    vkCmdPipelineBarrier2(cmd, &info);
}

/* ------------------------------------------------------------------ */
/*  Filter lifecycle                                                  */
/* ------------------------------------------------------------------ */

flux_result prism_liquid_glass_filter_create(flux_device *device,
                                             prism_liquid_glass_filter **out) {
    if (!device || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out = nullptr;
    prism_liquid_glass_filter *filter = calloc(1, sizeof(*filter));
    if (!filter)
        return FLUX_ERROR_OUT_OF_MEMORY;
    atomic_init(&filter->ref_count, 1u);
    filter->device = flux_device_retain(device);
    *out = filter;
    return FLUX_OK;
}

prism_liquid_glass_filter *prism_liquid_glass_filter_retain(prism_liquid_glass_filter *filter) {
    if (filter)
        atomic_fetch_add_explicit(&filter->ref_count, 1u, memory_order_relaxed);
    return filter;
}

void prism_liquid_glass_filter_release(prism_liquid_glass_filter *filter) {
    if (!filter)
        return;
    if (atomic_fetch_sub_explicit(&filter->ref_count, 1u, memory_order_acq_rel) != 1u)
        return;
    flux_device *device = filter->device;
    for (uint32_t i = 0; i < FLUX_MAX_FRAMES_IN_FLIGHT; ++i) {
        if (filter->slots[i].output)
            flux_image_release(filter->slots[i].output);
    }
    /* Pipelines are destroyed inline by flux; the header's release
     * contract (all referencing GPU work completed) covers this. */
    if (filter->glass_pipeline)
        flux_compute_pipeline_release(filter->glass_pipeline);
    if (filter->clear_pipeline)
        flux_compute_pipeline_release(filter->clear_pipeline);
    free(filter);
    flux_device_release(device);
}

static flux_result liquid_glass_ensure_slot(prism_liquid_glass_filter *filter, uint32_t index,
                                            const flux_image *input) {
    liquid_glass_filter_slot *slot = &filter->slots[index];
    uint32_t width = flux_image_width(input);
    uint32_t height = flux_image_height(input);
    if (slot->output && slot->width == width && slot->height == height)
        return FLUX_OK;
    if (slot->output)
        flux_image_release(slot->output);
    *slot = (liquid_glass_filter_slot){0};
    flux_result r = flux_image_create_compute_writable(filter->device, width, height,
                                                       PRISM_STORAGE_FORMAT, &slot->output);
    if (r != FLUX_OK)
        return r;
    slot->width = width;
    slot->height = height;
    return FLUX_OK;
}

/* The material pipelines are per-filter and lazily built: prism has no
 * per-device module state of its own, and the filter contract already
 * requires callers to serialize per device. */
static flux_result liquid_glass_ensure_pipelines(prism_liquid_glass_filter *filter, bool need_clear,
                                                 bool need_glass) {
    if (need_clear && !filter->clear_pipeline) {
        flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
        pdesc.spirv = (const uint32_t *)storage_clear_spv;
        pdesc.spirv_word_count = sizeof(storage_clear_spv) / sizeof(uint32_t);
        pdesc.entry_point = "main";
        pdesc.push_constant_bytes = sizeof(storage_clear_push);
        flux_result r = flux_compute_pipeline_create(filter->device, &pdesc, &filter->clear_pipeline);
        if (r != FLUX_OK)
            return r;
    }
    if (need_glass && !filter->glass_pipeline) {
        flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
        pdesc.spirv = (const uint32_t *)liquid_glass_spv;
        pdesc.spirv_word_count = sizeof(liquid_glass_spv) / sizeof(uint32_t);
        pdesc.entry_point = "main";
        pdesc.push_constant_bytes = sizeof(liquid_glass_push);
        flux_result r = flux_compute_pipeline_create(filter->device, &pdesc, &filter->glass_pipeline);
        if (r != FLUX_OK)
            return r;
    }
    return FLUX_OK;
}

/* ------------------------------------------------------------------ */
/*  Apply                                                             */
/* ------------------------------------------------------------------ */

static bool valid_liquid_glass_desc(const prism_liquid_glass_desc *desc) {
    if (desc->type != PRISM_TYPE_LIQUID_GLASS_DESC || !desc->input || !desc->blurred_input ||
        desc->group_count > LIQUID_GLASS_MAX_GROUPS || (desc->group_count > 0u && !desc->groups))
        return false;
    if (!isfinite(desc->refraction) || !isfinite(desc->chromatic_aberration) ||
        !isfinite(desc->saturation) || !isfinite(desc->brightness) || !isfinite(desc->edge_width) ||
        !isfinite(desc->rim_light) || !isfinite(desc->light_direction.x) ||
        !isfinite(desc->light_direction.y) || !isfinite(desc->opacity) ||
        !isfinite(desc->size_reference) || !isfinite(desc->size_scale_min) ||
        !isfinite(desc->tint_strength) || !isfinite(desc->frost_strength))
        return false;
    for (uint32_t i = 0; i < desc->group_count; ++i) {
        if (!liquid_glass_group_is_valid(&desc->groups[i]))
            return false;
    }
    return true;
}

static void copy_shape(float out[4], prism_liquid_glass_shape shape) {
    out[0] = shape.bounds.x;
    out[1] = shape.bounds.y;
    out[2] = shape.bounds.w;
    out[3] = shape.bounds.h;
}

static void record_storage_clear_regions(prism_liquid_glass_filter *filter, VkCommandBuffer command,
                                         flux_image *output, const liquid_glass_region *regions,
                                         uint32_t region_count) {
    for (uint32_t i = 0; i < region_count; ++i) {
        liquid_glass_region region = regions[i];
        storage_clear_push push = {
            .output_handle = flux_image_bindless_storage_handle(output),
            .width = flux_image_width(output),
            .height = flux_image_height(output),
            .origin_x = region.x,
            .origin_y = region.y,
            .region_width = region.width,
            .region_height = region.height,
        };
        uint32_t gx = (region.width + PRISM_WG - 1u) / PRISM_WG;
        uint32_t gy = (region.height + PRISM_WG - 1u) / PRISM_WG;
        flux_compute_dispatch(command, filter->clear_pipeline, &push, sizeof(push), gx, gy, 1u);
    }
}

flux_result prism_liquid_glass_filter_apply(prism_liquid_glass_filter *filter, flux_frame *frame,
                                            const prism_liquid_glass_desc *desc, flux_image **out) {
    if (!filter || !frame || !desc || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out = nullptr;
    if (!valid_liquid_glass_desc(desc))
        return FLUX_ERROR_INVALID_ARGUMENT;
    if (flux_frame_get_state(frame) != FLUX_FRAME_STATE_RECORDING ||
        flux_frame_has_active_pass(frame))
        return FLUX_ERROR_INVALID_STATE;
    flux_image *input = desc->input;
    flux_image *blurred = desc->blurred_input;
    if (flux_frame_device(frame) != filter->device || flux_image_device(input) != filter->device ||
        flux_image_device(blurred) != filter->device)
        return FLUX_ERROR_INVALID_ARGUMENT;
    if (flux_image_width(input) != flux_image_width(blurred) ||
        flux_image_height(input) != flux_image_height(blurred) ||
        (flux_image_format(input) != FLUX_FORMAT_RGBA8_UNORM &&
         flux_image_format(input) != FLUX_FORMAT_BGRA8_UNORM) ||
        flux_image_format(blurred) != FLUX_FORMAT_RGBA8_UNORM ||
        flux_image_bindless_handle(input) == FLUX_BINDLESS_INVALID ||
        flux_image_bindless_handle(blurred) == FLUX_BINDLESS_INVALID)
        return FLUX_ERROR_UNSUPPORTED;
    uint32_t index = flux_frame_index(frame);
    if (index >= FLUX_MAX_FRAMES_IN_FLIGHT)
        return FLUX_ERROR_OUT_OF_RANGE;
    flux_result result = liquid_glass_ensure_slot(filter, index, input);
    if (result != FLUX_OK)
        return result;

    uint32_t image_width = flux_image_width(input);
    uint32_t image_height = flux_image_height(input);
    liquid_glass_filter_slot *slot = &filter->slots[index];
    liquid_glass_region current[LIQUID_GLASS_MAX_GROUPS];
    uint32_t current_group_indices[LIQUID_GLASS_MAX_GROUPS];
    uint32_t current_count = 0u;
    for (uint32_t i = 0; i < desc->group_count; ++i) {
        const prism_liquid_glass_group *group = &desc->groups[i];
        /* The body's shadow reaches its downward offset plus the falloff. */
        float shadow_reach = group->shadow_alpha > 0.0f ? fmaxf(group->shadow_offset_y, 0.0f) +
                                                              2.0f * fmaxf(group->shadow_blur, 0.0f)
                                                        : 0.0f;
        liquid_glass_region region;
        if (!liquid_glass_group_dispatch_bounds(group, shadow_reach, image_width, image_height,
                                                &region))
            continue;
        current[current_count] = region;
        current_group_indices[current_count] = i;
        ++current_count;
    }

    liquid_glass_region clear_regions[LIQUID_GLASS_MAX_CLEAR_REGIONS];
    uint32_t clear_count = 0u;
    if (!liquid_glass_build_clear_regions(
            slot->initialized, image_width, image_height, slot->previous, slot->previous_count,
            current, current_count, clear_regions, LIQUID_GLASS_MAX_CLEAR_REGIONS, &clear_count))
        return FLUX_ERROR_INVALID_STATE;

    result = liquid_glass_ensure_pipelines(filter, clear_count > 0u, current_count > 0u);
    if (result != FLUX_OK)
        return result;

    VkCommandBuffer command = flux_frame_vk_command_buffer(frame);
    VkImage output_image = flux_image_vk_image(slot->output);
    if (clear_count > 0u) {
        if (slot->initialized)
            barrier_reuse_to_compute_write(command, output_image);
        record_storage_clear_regions(filter, command, slot->output, clear_regions, clear_count);
        if (current_count > 0u)
            barrier_compute_write_to_read_write(command, output_image);
    }

    bool dispatched = false;
    for (uint32_t i = 0; i < current_count; ++i) {
        const prism_liquid_glass_group *group = &desc->groups[current_group_indices[i]];
        liquid_glass_region region = current[i];
        if (dispatched)
            barrier_compute_write_to_read_write(command, output_image);
        liquid_glass_push push = {
            .input_handle = flux_image_bindless_handle(input),
            .blurred_handle = flux_image_bindless_handle(blurred),
            .sampler_handle = flux_device_default_sampler_handle(filter->device),
            .output_handle = flux_image_bindless_storage_handle(slot->output),
            .width = image_width,
            .height = image_height,
            .origin_x = region.x,
            .origin_y = region.y,
            .radius0 = fmaxf(group->shapes[0].corner_radius, 0.0f),
            .radius1 = group->focus_strength > 0.0f
                           ? fmaxf(group->focus.corner_radius, 0.0f)
                           : (group->shape_count == 2u ? fmaxf(group->shapes[1].corner_radius, 0.0f)
                                                       : 0.0f),
            .blend_radius = fmaxf(group->blend_radius, 0.0f),
            .opacity = fminf(fmaxf(group->opacity * desc->opacity, 0.0f), 1.0f),
            .refraction = fmaxf(desc->refraction, 0.0f),
            .chromatic_aberration = fmaxf(desc->chromatic_aberration, 0.0f),
            .saturation = fmaxf(desc->saturation, 0.0f),
            .brightness = fmaxf(desc->brightness, 0.0f),
            .edge_width = fmaxf(desc->edge_width, 1.0f),
            .rim_light = fmaxf(desc->rim_light, 0.0f),
            .light_x = desc->light_direction.x,
            .light_y = desc->light_direction.y,
            .group_width = region.width,
            .group_height = region.height,
            .shape_count = group->shape_count,
            .shadow_alpha = fminf(fmaxf(group->shadow_alpha, 0.0f), 1.0f),
            .shadow_blur = fmaxf(group->shadow_blur, 0.0f),
            .shadow_offset_y = group->shadow_offset_y,
            .size_reference = fmaxf(desc->size_reference, 0.0f),
            .size_scale_min = fminf(fmaxf(desc->size_scale_min, 0.0f), 1.0f),
            .tint_strength = fmaxf(desc->tint_strength, 0.0f),
            .frost_strength = fmaxf(desc->frost_strength, 0.0f),
            .tint_color = group->tint_color,
            .focus_strength = fminf(fmaxf(group->focus_strength, 0.0f), 1.0f),
        };
        copy_shape(push.shape0, group->shapes[0]);
        if (group->focus_strength > 0.0f)
            copy_shape(push.shape1, group->focus);
        else if (group->shape_count == 2u)
            copy_shape(push.shape1, group->shapes[1]);
        uint32_t gx = (region.width + PRISM_WG - 1u) / PRISM_WG;
        uint32_t gy = (region.height + PRISM_WG - 1u) / PRISM_WG;
        flux_compute_dispatch(command, filter->glass_pipeline, &push, sizeof(push), gx, gy, 1u);
        dispatched = true;
    }
    /* Both the transparent region clear and liquid material are compute
     * storage writes. Make the persistent output visible to its following
     * Canvas sample, including a clear-only apply after all groups disappear. */
    if (clear_count > 0u || dispatched)
        barrier_compute_write_to_read(command, output_image);

    if (current_count > 0u)
        memcpy(slot->previous, current, current_count * sizeof(current[0]));
    slot->previous_count = current_count;
    slot->initialized = true;
    *out = slot->output;
    return FLUX_OK;
}
