/*
 * Analytic liquid-glass material — the convex-lens model of ADR-0046 with
 * the focus field of ADR-0050.
 *
 * prism is a separate library from flux: this file is implemented entirely
 * on flux's public API (compute pipelines, compute-writable images,
 * frame-slot queries, the bindless heap, raw Vulkan handle accessors).
 * flux owns the effect runtime; the material — its shader, the regions
 * policy below, and this dispatch machinery — lives here (ADR-0063).
 *
 * Layout:
 *   - shader bytecode (#embed or generated headers, same idiom as flux)
 *   - push-constant blocks matching the shaders
 *   - barrier helpers (raw Vulkan over flux_image_vk_image)
 *   - the frame-slot filter: per-slot output, footprint clearing, dispatch
 */

#include <prism/liquid_glass.h>

#include <flux/compute.h>
#include <flux/vulkan.h>

#include "regions.h"

#include <math.h>
#include <stdalign.h>
#include <stdatomic.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

/* Shader bytecode: C23 #embed, or generated headers (tools/spv2h.py)
 * where the compiler lacks it — same idiom as flux's renderer. */
#if defined(__has_embed) && !defined(PRISM_SHADER_NO_EMBED)
#if __has_embed("liquid_glass.comp.spv") && __has_embed("storage_clear.comp.spv") && \
    __has_embed("backdrop_stats.comp.spv")
#define PRISM_SHADERS_EMBED 1
#endif
#endif

#ifdef PRISM_SHADERS_EMBED
alignas(uint32_t) static const unsigned char liquid_glass_spv[] = {
#embed "liquid_glass.comp.spv"
};

alignas(uint32_t) static const unsigned char storage_clear_spv[] = {
#embed "storage_clear.comp.spv"
};

alignas(uint32_t) static const unsigned char backdrop_stats_spv[] = {
#embed "backdrop_stats.comp.spv"
};
#else
#include "liquid_glass_spv.h"
#include "storage_clear_spv.h"  /* generated by tools/spv2h.py; same arrays */
#include "backdrop_stats_spv.h" /* generated by tools/spv2h.py; same arrays */
#endif

/* Push-constant block — must match liquid_glass.comp exactly. The budget is
 * exactly 160 bytes, so two pairs are bit-packed: tint_color_shape_count is
 * the 24-bit 0xRRGGBB tint with shape_count (1 or 2) in the top byte, and
 * size_params is size_reference/size_scale_min as two IEEE-754 binary16
 * halves (the shader unpacks with unpackHalf2x16). */
typedef struct liquid_glass_push {
    uint32_t input_handle;
    uint32_t blurred_handle;
    uint32_t sampler_handle;
    uint32_t output_handle;
    uint32_t width;
    uint32_t height;
    uint32_t origin_x;
    uint32_t origin_y;
    float shape0[4];
    float shape1[4];
    float radius0;
    float radius1;
    float blend_radius;
    float opacity;
    float refraction;
    float chromatic_aberration;
    float saturation;
    float brightness;
    float edge_width;
    float rim_light;
    float light_x;
    float light_y;
    uint32_t group_width;
    uint32_t group_height;
    uint32_t tint_color_shape_count;
    float shadow_alpha;
    float shadow_blur;
    float shadow_offset_y;
    uint32_t size_params;
    float tint_strength;
    float frost_strength;
    float focus_strength;
    float plate_polarity;
    float backdrop_energy;
} liquid_glass_push;

/* Push-constant block — must match storage_clear.comp exactly. */
typedef struct storage_clear_push {
    uint32_t output_handle;
    uint32_t width;
    uint32_t height;
    uint32_t origin_x;
    uint32_t origin_y;
    uint32_t region_width;
    uint32_t region_height;
} storage_clear_push;

/* Push-constant block — must match backdrop_stats.comp exactly. The stats
 * buffer's 64-bit device address rides as two u32s because flux devices do
 * not guarantee shaderInt64. */
typedef struct backdrop_stats_push {
    uint32_t input_handle;
    uint32_t blurred_handle;
    uint32_t sampler_handle;
    uint32_t width;
    uint32_t height;
    uint32_t rect_x;
    uint32_t rect_y;
    uint32_t rect_width;
    uint32_t rect_height;
    uint32_t group_index;
    uint32_t stats_address_lo;
    uint32_t stats_address_hi;
} backdrop_stats_push;

/* flux requires every device to accept 160 push-constant bytes, so the
 * material can rely on that budget on any flux device. */
static_assert(sizeof(liquid_glass_push) == 160,
              "liquid_glass_push no longer matches its shader block");
static_assert(sizeof(storage_clear_push) == 28,
              "storage_clear_push no longer matches its shader block");
static_assert(sizeof(backdrop_stats_push) == 48,
              "backdrop_stats_push no longer matches its shader block");

/* Per-slot stats buffer: one prism_backdrop_stat per group. */
#define PRISM_STATS_BYTES (LIQUID_GLASS_MAX_GROUPS * 2u * sizeof(float))

/* IEEE-754 binary32 → binary16, round-to-nearest-even, for the packed
 * size_reference/size_scale_min push slot. Inputs are validated finite and
 * clamped non-negative by the caller; the full subnormal/overflow rounding
 * is still handled so any finite float converts correctly. */
static uint16_t liquid_glass_f32_to_f16(float value) {
    uint32_t bits;
    memcpy(&bits, &value, sizeof(bits));
    uint32_t sign = (bits >> 16u) & 0x8000u;
    uint32_t exponent = (bits >> 23u) & 0xFFu;
    uint32_t mantissa = bits & 0x7FFFFFu;

    if (exponent == 0xFFu) /* inf/nan (validation rejects nan) → f16 inf */
        return (uint16_t)(sign | 0x7C00u);

    int half_exp = (int)exponent - 127 + 15;
    if (half_exp >= 0x1F) /* overflow → f16 inf */
        return (uint16_t)(sign | 0x7C00u);
    if (half_exp <= 0) {
        /* f16 subnormal or signed zero. */
        if (half_exp < -10)
            return (uint16_t)sign;
        mantissa |= 0x800000u; /* restore the hidden bit */
        uint32_t shift = (uint32_t)(14 - half_exp); /* 13..24 */
        uint32_t half = mantissa >> shift;
        uint32_t remainder = mantissa & ((1u << shift) - 1u);
        uint32_t halfway = 1u << (shift - 1u);
        if (remainder > halfway || (remainder == halfway && (half & 1u)))
            ++half; /* may carry into the exponent field — correct */
        return (uint16_t)(sign | half);
    }
    /* Normal f16: round the 13 dropped mantissa bits, nearest-even. */
    uint32_t half = sign | ((uint32_t)half_exp << 10u) | (mantissa >> 13u);
    uint32_t remainder = mantissa & 0x1FFFu;
    if (remainder > 0x1000u || (remainder == 0x1000u && (half & 1u)))
        ++half; /* mantissa overflow carries into the exponent — correct */
    return (uint16_t)half;
}

#define PRISM_WG 16u
#define PRISM_STORAGE_FORMAT FLUX_FORMAT_RGBA8_UNORM

typedef struct liquid_glass_filter_slot {
    uint32_t width;
    uint32_t height;
    flux_image *output;
    bool initialized;
    uint32_t previous_count;
    liquid_glass_region previous[LIQUID_GLASS_MAX_GROUPS];
    /* Per-slot backdrop statistics: one HOST_VISIBLE storage buffer written
     * by the stats dispatch and read back FLUX_MAX_FRAMES_IN_FLIGHT frames
     * later, once begin_frame has waited this slot's fence. */
    flux_buffer *stats;
    bool stats_submitted;
    uint32_t stats_group_count;
} liquid_glass_filter_slot;

struct prism_liquid_glass_filter {
    atomic_uint ref_count;
    flux_device *device; /* retained; slot images hold weak device refs */
    flux_compute_pipeline *glass_pipeline; /* lazily built on first apply */
    flux_compute_pipeline *clear_pipeline;
    flux_compute_pipeline *stats_pipeline;
    liquid_glass_filter_slot slots[FLUX_MAX_FRAMES_IN_FLIGHT];
};

/* ------------------------------------------------------------------ */
/*  Barrier helpers (raw Vulkan over flux_image_vk_image)             */
/* ------------------------------------------------------------------ */

/* Emit a compute-write → compute-read barrier on `image`, no layout
 * transition (image stays in GENERAL). Makes the output sampleable by any
 * later shader stage. */
static void barrier_compute_write_to_read(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask =
            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_READ_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* A reusable frame-slot image may have been sampled by the slot's previous
 * submission. begin_frame waited that slot's fence; this barrier expresses
 * the device-side read/write dependency before the next compute overwrite. */
static void barrier_reuse_to_compute_write(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask =
            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* Groups source-over the persistent storage image. Make an earlier group's
 * write visible to both imageLoad and imageStore in the next group; a
 * write-only dependency lets a later shadow replace the body below it
 * instead of compositing over it. */
static void barrier_compute_write_to_read_write(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 barrier = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo info = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &barrier,
    };
    vkCmdPipelineBarrier2(cmd, &info);
}

/* Make a stats-buffer compute write visible to the next submission's
 * compute read/write on the same buffer. Host visibility needs no barrier
 * here: the slot's frame fence plus the HOST_COHERENT mapping cover the
 * CPU readback path. */
static void barrier_stats_write_to_compute(VkCommandBuffer cmd, VkBuffer buffer) {
    VkBufferMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .buffer = buffer,
        .offset = 0,
        .size = VK_WHOLE_SIZE,
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .bufferMemoryBarrierCount = 1,
        .pBufferMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* ------------------------------------------------------------------ */
/*  Filter lifecycle                                                  */
/* ------------------------------------------------------------------ */

flux_result prism_liquid_glass_filter_create(flux_device *device,
                                             prism_liquid_glass_filter **out) {
    if (!device || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out = nullptr;
    prism_liquid_glass_filter *filter = calloc(1, sizeof(*filter));
    if (!filter)
        return FLUX_ERROR_OUT_OF_MEMORY;
    atomic_init(&filter->ref_count, 1u);
    filter->device = flux_device_retain(device);
    *out = filter;
    return FLUX_OK;
}

prism_liquid_glass_filter *prism_liquid_glass_filter_retain(prism_liquid_glass_filter *filter) {
    if (filter)
        atomic_fetch_add_explicit(&filter->ref_count, 1u, memory_order_relaxed);
    return filter;
}

void prism_liquid_glass_filter_release(prism_liquid_glass_filter *filter) {
    if (!filter)
        return;
    if (atomic_fetch_sub_explicit(&filter->ref_count, 1u, memory_order_acq_rel) != 1u)
        return;
    flux_device *device = filter->device;
    for (uint32_t i = 0; i < FLUX_MAX_FRAMES_IN_FLIGHT; ++i) {
        if (filter->slots[i].output)
            flux_image_release(filter->slots[i].output);
        if (filter->slots[i].stats)
            flux_buffer_release(filter->slots[i].stats);
    }
    /* Pipelines are destroyed inline by flux; the header's release
     * contract (all referencing GPU work completed) covers this. */
    if (filter->glass_pipeline)
        flux_compute_pipeline_release(filter->glass_pipeline);
    if (filter->clear_pipeline)
        flux_compute_pipeline_release(filter->clear_pipeline);
    if (filter->stats_pipeline)
        flux_compute_pipeline_release(filter->stats_pipeline);
    free(filter);
    flux_device_release(device);
}

static flux_result liquid_glass_ensure_stats_buffer(prism_liquid_glass_filter *filter,
                                                    liquid_glass_filter_slot *slot) {
    if (slot->stats)
        return FLUX_OK;
    flux_buffer_desc bdesc = FLUX_BUFFER_DESC_INIT;
    bdesc.size = PRISM_STATS_BYTES;
    bdesc.usage = FLUX_BUFFER_USAGE_STORAGE;
    /* HOST_VISIBLE is HOST_COHERENT in flux: the shader's writes are
     * visible to the CPU after the slot's fence, no flush/invalidate. */
    bdesc.location = FLUX_BUFFER_HOST_VISIBLE;
    bdesc.device_address = true; /* stats shader writes via buffer reference */
    return flux_buffer_create(filter->device, &bdesc, &slot->stats);
}

static flux_result liquid_glass_ensure_slot(prism_liquid_glass_filter *filter, uint32_t index,
                                            const flux_image *input, bool need_stats) {
    liquid_glass_filter_slot *slot = &filter->slots[index];
    uint32_t width = flux_image_width(input);
    uint32_t height = flux_image_height(input);
    if (slot->output && slot->width == width && slot->height == height)
        return need_stats ? liquid_glass_ensure_stats_buffer(filter, slot) : FLUX_OK;
    if (slot->output)
        flux_image_release(slot->output);
    if (slot->stats)
        flux_buffer_release(slot->stats);
    *slot = (liquid_glass_filter_slot){0};
    flux_result r = flux_image_create_compute_writable(filter->device, width, height,
                                                       PRISM_STORAGE_FORMAT, &slot->output);
    if (r != FLUX_OK)
        return r;
    slot->width = width;
    slot->height = height;
    if (need_stats) {
        r = liquid_glass_ensure_stats_buffer(filter, slot);
        if (r != FLUX_OK)
            return r;
    }
    return FLUX_OK;
}

/* The material pipelines are per-filter and lazily built: prism has no
 * per-device module state of its own, and the filter contract already
 * requires callers to serialize per device. */
static flux_result liquid_glass_ensure_pipelines(prism_liquid_glass_filter *filter, bool need_clear,
                                                 bool need_glass, bool need_stats) {
    if (need_clear && !filter->clear_pipeline) {
        flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
        pdesc.spirv = (const uint32_t *)storage_clear_spv;
        pdesc.spirv_word_count = sizeof(storage_clear_spv) / sizeof(uint32_t);
        pdesc.entry_point = "main";
        pdesc.push_constant_bytes = sizeof(storage_clear_push);
        flux_result r = flux_compute_pipeline_create(filter->device, &pdesc, &filter->clear_pipeline);
        if (r != FLUX_OK)
            return r;
    }
    if (need_glass && !filter->glass_pipeline) {
        flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
        pdesc.spirv = (const uint32_t *)liquid_glass_spv;
        pdesc.spirv_word_count = sizeof(liquid_glass_spv) / sizeof(uint32_t);
        pdesc.entry_point = "main";
        pdesc.push_constant_bytes = sizeof(liquid_glass_push);
        flux_result r = flux_compute_pipeline_create(filter->device, &pdesc, &filter->glass_pipeline);
        if (r != FLUX_OK)
            return r;
    }
    if (need_stats && !filter->stats_pipeline) {
        flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
        pdesc.spirv = (const uint32_t *)backdrop_stats_spv;
        pdesc.spirv_word_count = sizeof(backdrop_stats_spv) / sizeof(uint32_t);
        pdesc.entry_point = "main";
        pdesc.push_constant_bytes = sizeof(backdrop_stats_push);
        flux_result r = flux_compute_pipeline_create(filter->device, &pdesc, &filter->stats_pipeline);
        if (r != FLUX_OK)
            return r;
    }
    return FLUX_OK;
}

/* ------------------------------------------------------------------ */
/*  Apply                                                             */
/* ------------------------------------------------------------------ */

static bool valid_liquid_glass_desc(const prism_liquid_glass_desc *desc) {
    if (desc->type != PRISM_TYPE_LIQUID_GLASS_DESC || !desc->input || !desc->blurred_input ||
        desc->group_count > LIQUID_GLASS_MAX_GROUPS || (desc->group_count > 0u && !desc->groups))
        return false;
    if (!isfinite(desc->refraction) || !isfinite(desc->chromatic_aberration) ||
        !isfinite(desc->saturation) || !isfinite(desc->brightness) || !isfinite(desc->edge_width) ||
        !isfinite(desc->rim_light) || !isfinite(desc->light_direction.x) ||
        !isfinite(desc->light_direction.y) || !isfinite(desc->opacity) ||
        !isfinite(desc->size_reference) || !isfinite(desc->size_scale_min) ||
        !isfinite(desc->tint_strength) || !isfinite(desc->frost_strength))
        return false;
    for (uint32_t i = 0; i < desc->group_count; ++i) {
        if (!liquid_glass_group_is_valid(&desc->groups[i]))
            return false;
    }
    return true;
}

static void copy_shape(float out[4], prism_liquid_glass_shape shape) {
    out[0] = shape.bounds.x;
    out[1] = shape.bounds.y;
    out[2] = shape.bounds.w;
    out[3] = shape.bounds.h;
}

static void record_storage_clear_regions(prism_liquid_glass_filter *filter, VkCommandBuffer command,
                                         flux_image *output, const liquid_glass_region *regions,
                                         uint32_t region_count) {
    for (uint32_t i = 0; i < region_count; ++i) {
        liquid_glass_region region = regions[i];
        storage_clear_push push = {
            .output_handle = flux_image_bindless_storage_handle(output),
            .width = flux_image_width(output),
            .height = flux_image_height(output),
            .origin_x = region.x,
            .origin_y = region.y,
            .region_width = region.width,
            .region_height = region.height,
        };
        uint32_t gx = (region.width + PRISM_WG - 1u) / PRISM_WG;
        uint32_t gy = (region.height + PRISM_WG - 1u) / PRISM_WG;
        flux_compute_dispatch(command, filter->clear_pipeline, &push, sizeof(push), gx, gy, 1u);
    }
}

flux_result prism_liquid_glass_filter_apply(prism_liquid_glass_filter *filter, flux_frame *frame,
                                            const prism_liquid_glass_desc *desc, flux_image **out) {
    if (!filter || !frame || !desc || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out = nullptr;
    if (!valid_liquid_glass_desc(desc))
        return FLUX_ERROR_INVALID_ARGUMENT;
    if (flux_frame_get_state(frame) != FLUX_FRAME_STATE_RECORDING ||
        flux_frame_has_active_pass(frame))
        return FLUX_ERROR_INVALID_STATE;
    flux_image *input = desc->input;
    flux_image *blurred = desc->blurred_input;
    if (flux_frame_device(frame) != filter->device || flux_image_device(input) != filter->device ||
        flux_image_device(blurred) != filter->device)
        return FLUX_ERROR_INVALID_ARGUMENT;
    if (flux_image_width(input) != flux_image_width(blurred) ||
        flux_image_height(input) != flux_image_height(blurred) ||
        (flux_image_format(input) != FLUX_FORMAT_RGBA8_UNORM &&
         flux_image_format(input) != FLUX_FORMAT_BGRA8_UNORM) ||
        flux_image_format(blurred) != FLUX_FORMAT_RGBA8_UNORM ||
        flux_image_bindless_handle(input) == FLUX_BINDLESS_INVALID ||
        flux_image_bindless_handle(blurred) == FLUX_BINDLESS_INVALID)
        return FLUX_ERROR_UNSUPPORTED;
    uint32_t index = flux_frame_index(frame);
    if (index >= FLUX_MAX_FRAMES_IN_FLIGHT)
        return FLUX_ERROR_OUT_OF_RANGE;
    flux_result result = liquid_glass_ensure_slot(filter, index, input, desc->group_count > 0u);
    if (result != FLUX_OK)
        return result;

    uint32_t image_width = flux_image_width(input);
    uint32_t image_height = flux_image_height(input);
    liquid_glass_filter_slot *slot = &filter->slots[index];
    liquid_glass_region current[LIQUID_GLASS_MAX_GROUPS];
    uint32_t current_group_indices[LIQUID_GLASS_MAX_GROUPS];
    uint32_t current_count = 0u;
    for (uint32_t i = 0; i < desc->group_count; ++i) {
        const prism_liquid_glass_group *group = &desc->groups[i];
        /* The body's shadow reaches its downward offset plus the falloff. */
        float shadow_reach = group->shadow_alpha > 0.0f ? fmaxf(group->shadow_offset_y, 0.0f) +
                                                              2.0f * fmaxf(group->shadow_blur, 0.0f)
                                                        : 0.0f;
        liquid_glass_region region;
        if (!liquid_glass_group_dispatch_bounds(group, shadow_reach, image_width, image_height,
                                                &region))
            continue;
        current[current_count] = region;
        current_group_indices[current_count] = i;
        ++current_count;
    }

    liquid_glass_region clear_regions[LIQUID_GLASS_MAX_CLEAR_REGIONS];
    uint32_t clear_count = 0u;
    if (!liquid_glass_build_clear_regions(
            slot->initialized, image_width, image_height, slot->previous, slot->previous_count,
            current, current_count, clear_regions, LIQUID_GLASS_MAX_CLEAR_REGIONS, &clear_count))
        return FLUX_ERROR_INVALID_STATE;

    result = liquid_glass_ensure_pipelines(filter, clear_count > 0u, current_count > 0u,
                                           desc->group_count > 0u);
    if (result != FLUX_OK)
        return result;

    VkCommandBuffer command = flux_frame_vk_command_buffer(frame);
    VkImage output_image = flux_image_vk_image(slot->output);
    if (clear_count > 0u) {
        if (slot->initialized)
            barrier_reuse_to_compute_write(command, output_image);
        record_storage_clear_regions(filter, command, slot->output, clear_regions, clear_count);
        if (current_count > 0u)
            barrier_compute_write_to_read_write(command, output_image);
    }

    /* Backdrop statistics: one 16x16 workgroup per group reduces the
     * primary body's backdrop into (mean luminance, high-frequency energy)
     * for the frame-lagged CPU read. Off-screen bodies reduce an empty
     * rect, which the shader reports as zeros. Runs before the glass
     * dispatches; it shares only their sampled inputs. */
    if (desc->group_count > 0u) {
        uint64_t stats_address = flux_buffer_device_address(slot->stats);
        for (uint32_t i = 0; i < desc->group_count; ++i) {
            liquid_glass_region rect =
                liquid_glass_group_stats_bounds(&desc->groups[i], image_width, image_height);
            backdrop_stats_push spush = {
                .input_handle = flux_image_bindless_handle(input),
                .blurred_handle = flux_image_bindless_handle(blurred),
                .sampler_handle = flux_device_default_sampler_handle(filter->device),
                .width = image_width,
                .height = image_height,
                .rect_x = rect.x,
                .rect_y = rect.y,
                .rect_width = rect.width,
                .rect_height = rect.height,
                .group_index = i,
                .stats_address_lo = (uint32_t)(stats_address & 0xFFFFFFFFu),
                .stats_address_hi = (uint32_t)(stats_address >> 32u),
            };
            flux_compute_dispatch(command, filter->stats_pipeline, &spush, sizeof(spush), 1u, 1u,
                                  1u);
        }
        barrier_stats_write_to_compute(command, flux_buffer_vk_buffer(slot->stats));
    }

    bool dispatched = false;
    for (uint32_t i = 0; i < current_count; ++i) {
        const prism_liquid_glass_group *group = &desc->groups[current_group_indices[i]];
        liquid_glass_region region = current[i];
        if (dispatched)
            barrier_compute_write_to_read_write(command, output_image);
        /* Per-group overrides: a negative value inherits the desc knob. */
        float saturation = liquid_glass_group_or_desc(group->saturation, desc->saturation);
        float tint_strength = liquid_glass_group_or_desc(group->tint_strength, desc->tint_strength);
        float frost_strength =
            liquid_glass_group_or_desc(group->frost_strength, desc->frost_strength);
        float size_reference = fmaxf(desc->size_reference, 0.0f);
        float size_scale_min = fminf(fmaxf(desc->size_scale_min, 0.0f), 1.0f);
        liquid_glass_push push = {
            .input_handle = flux_image_bindless_handle(input),
            .blurred_handle = flux_image_bindless_handle(blurred),
            .sampler_handle = flux_device_default_sampler_handle(filter->device),
            .output_handle = flux_image_bindless_storage_handle(slot->output),
            .width = image_width,
            .height = image_height,
            .origin_x = region.x,
            .origin_y = region.y,
            .radius0 = fmaxf(group->shapes[0].corner_radius, 0.0f),
            .radius1 = group->focus_strength > 0.0f
                           ? fmaxf(group->focus.corner_radius, 0.0f)
                           : (group->shape_count == 2u ? fmaxf(group->shapes[1].corner_radius, 0.0f)
                                                       : 0.0f),
            .blend_radius = fmaxf(group->blend_radius, 0.0f),
            .opacity = fminf(fmaxf(group->opacity * desc->opacity, 0.0f), 1.0f),
            .refraction = fmaxf(desc->refraction, 0.0f),
            .chromatic_aberration = fmaxf(desc->chromatic_aberration, 0.0f),
            .saturation = fmaxf(saturation, 0.0f),
            .brightness = fmaxf(desc->brightness, 0.0f),
            .edge_width = fmaxf(desc->edge_width, 1.0f),
            .rim_light = fmaxf(desc->rim_light, 0.0f),
            .light_x = desc->light_direction.x,
            .light_y = desc->light_direction.y,
            .group_width = region.width,
            .group_height = region.height,
            .tint_color_shape_count = (group->tint_color & 0x00FFFFFFu) | (group->shape_count << 24u),
            .shadow_alpha = fminf(fmaxf(group->shadow_alpha, 0.0f), 1.0f),
            .shadow_blur = fmaxf(group->shadow_blur, 0.0f),
            .shadow_offset_y = group->shadow_offset_y,
            .size_params = (uint32_t)liquid_glass_f32_to_f16(size_reference) |
                           ((uint32_t)liquid_glass_f32_to_f16(size_scale_min) << 16u),
            .tint_strength = fmaxf(tint_strength, 0.0f),
            .frost_strength = fmaxf(frost_strength, 0.0f),
            .focus_strength = fminf(fmaxf(group->focus_strength, 0.0f), 1.0f),
            .plate_polarity = group->plate_polarity,
            .backdrop_energy = group->backdrop_energy,
        };
        copy_shape(push.shape0, group->shapes[0]);
        if (group->focus_strength > 0.0f)
            copy_shape(push.shape1, group->focus);
        else if (group->shape_count == 2u)
            copy_shape(push.shape1, group->shapes[1]);
        uint32_t gx = (region.width + PRISM_WG - 1u) / PRISM_WG;
        uint32_t gy = (region.height + PRISM_WG - 1u) / PRISM_WG;
        flux_compute_dispatch(command, filter->glass_pipeline, &push, sizeof(push), gx, gy, 1u);
        dispatched = true;
    }
    /* Both the transparent region clear and liquid material are compute
     * storage writes. Make the persistent output visible to its following
     * Canvas sample, including a clear-only apply after all groups disappear. */
    if (clear_count > 0u || dispatched)
        barrier_compute_write_to_read(command, output_image);

    if (current_count > 0u)
        memcpy(slot->previous, current, current_count * sizeof(current[0]));
    slot->previous_count = current_count;
    slot->initialized = true;
    slot->stats_submitted = true;
    /* A zero-group apply submits no stats; the frame-lagged read then
     * honestly reports zero groups for this slot's last submission. */
    slot->stats_group_count = desc->group_count;
    *out = slot->output;
    return FLUX_OK;
}

flux_result prism_liquid_glass_filter_stats(prism_liquid_glass_filter *filter, flux_frame *frame,
                                            prism_backdrop_stat *out, uint32_t max_groups,
                                            uint32_t *out_count) {
    if (!filter || !frame || !out_count || (max_groups > 0u && !out))
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out_count = 0u;
    if (flux_frame_device(frame) != filter->device)
        return FLUX_ERROR_INVALID_ARGUMENT;
    /* The mapped buffer is stable only while this frame records: its
     * begin_frame waited the slot's fence. */
    if (flux_frame_get_state(frame) != FLUX_FRAME_STATE_RECORDING)
        return FLUX_ERROR_INVALID_STATE;
    uint32_t index = flux_frame_index(frame);
    if (index >= FLUX_MAX_FRAMES_IN_FLIGHT)
        return FLUX_ERROR_OUT_OF_RANGE;
    const liquid_glass_filter_slot *slot = &filter->slots[index];
    if (!slot->stats_submitted || !slot->stats)
        return FLUX_ERROR_INVALID_STATE;
    uint32_t count =
        slot->stats_group_count < max_groups ? slot->stats_group_count : max_groups;
    if (count > 0u)
        memcpy(out, flux_buffer_mapped(slot->stats), count * sizeof(*out));
    *out_count = count;
    return FLUX_OK;
}
