/*
 * Analytic liquid-glass material — the convex-lens model of ADR-0046 with
 * the focus field of ADR-0050.
 *
 * prism is a separate library from flux: this file is implemented entirely
 * on flux's public API (compute pipelines, compute-writable images,
 * frame-slot queries, the bindless heap, raw Vulkan handle accessors).
 * flux owns the effect runtime; the material — its shader, the regions
 * policy below, and this dispatch machinery — lives here (ADR-0063).
 *
 * Layout:
 *   - shader bytecode (#embed or generated headers, same idiom as flux)
 *   - push-constant blocks matching the shaders
 *   - barrier helpers (raw Vulkan over flux_image_vk_image)
 *   - the frame-slot filter: per-slot output, footprint clearing, dispatch
 */

#include <prism/liquid_glass.h>

#include <flux/compute.h>
#include <flux/vulkan.h>

#include "glass_dispatch.h"
#include "regions.h"

#include <math.h>
#include <stdalign.h>
#include <stdatomic.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

/* Shader bytecode: C23 #embed, or generated headers (tools/spv2h.py)
 * where the compiler lacks it — same idiom as flux's renderer. */
#if defined(__has_embed) && !defined(PRISM_SHADER_NO_EMBED)
#if __has_embed("liquid_glass.comp.spv") && __has_embed("storage_clear.comp.spv") &&               \
    __has_embed("backdrop_stats.comp.spv") && __has_embed("liquid_glass_16f.comp.spv") &&          \
    __has_embed("storage_clear_16f.comp.spv")
#define PRISM_SHADERS_EMBED 1
#endif
#endif

#ifdef PRISM_SHADERS_EMBED
alignas(uint32_t) static const unsigned char liquid_glass_spv[] = {
#embed "liquid_glass.comp.spv"
};

alignas(uint32_t) static const unsigned char storage_clear_spv[] = {
#embed "storage_clear.comp.spv"
};

alignas(uint32_t) static const unsigned char backdrop_stats_spv[] = {
#embed "backdrop_stats.comp.spv"
};

/* ADR-0069: rgba16f storage variants for working-space (16F) inputs. */
alignas(uint32_t) static const unsigned char liquid_glass_16f_spv[] = {
#embed "liquid_glass_16f.comp.spv"
};

alignas(uint32_t) static const unsigned char storage_clear_16f_spv[] = {
#embed "storage_clear_16f.comp.spv"
};
#else
#include "backdrop_stats_spv.h" /* generated by tools/spv2h.py; same arrays */
#include "liquid_glass_16f_spv.h"
#include "liquid_glass_spv.h"
#include "storage_clear_16f_spv.h"
#include "storage_clear_spv.h"
#endif

/* Push-constant block — must match storage_clear.comp exactly. */
typedef struct storage_clear_push {
    uint32_t output_handle;
    uint32_t width;
    uint32_t height;
    uint32_t origin_x;
    uint32_t origin_y;
    uint32_t region_width;
    uint32_t region_height;
} storage_clear_push;

/* Push-constant block — must match backdrop_stats.comp exactly. The stats
 * buffer's 64-bit device address rides as two u32s because flux devices do
 * not guarantee shaderInt64. */
typedef struct backdrop_stats_push {
    uint32_t input_handle;
    uint32_t blurred_handle;
    uint32_t sampler_handle;
    uint32_t width;
    uint32_t height;
    uint32_t rect_x;
    uint32_t rect_y;
    uint32_t rect_width;
    uint32_t rect_height;
    uint32_t group_index;
    uint32_t stats_address_lo;
    uint32_t stats_address_hi;
} backdrop_stats_push;

/* flux requires every device to accept 160 push-constant bytes, so the
 * material can rely on that budget on any flux device. */
static_assert(sizeof(storage_clear_push) == 28,
              "storage_clear_push no longer matches its shader block");
static_assert(sizeof(backdrop_stats_push) == 48,
              "backdrop_stats_push no longer matches its shader block");

/* Per-slot stats buffer: one prism_backdrop_stat per group. */
#define PRISM_STATS_BYTES (LIQUID_GLASS_MAX_GROUPS * 2u * sizeof(float))

/* The material output container follows the input (ADR-0069): 8-bit SDR
 * inputs produce the historic RGBA8 output; 16F working-space inputs a
 * 16F output, so the material composites in linear light. */
static flux_format prism_output_format(const flux_image *input) {
    return flux_image_format(input) == FLUX_FORMAT_RGBA16_SFLOAT ? FLUX_FORMAT_RGBA16_SFLOAT
                                                                 : FLUX_FORMAT_RGBA8_UNORM;
}

typedef struct liquid_glass_filter_slot {
    uint32_t width;
    uint32_t height;
    flux_format format; /* of `output` */
    flux_image *output;
    bool initialized;
    uint32_t previous_count;
    liquid_glass_region previous[LIQUID_GLASS_MAX_GROUPS];
    /* Per-slot backdrop statistics: one HOST_VISIBLE storage buffer written
     * by the stats dispatch and read back FLUX_MAX_FRAMES_IN_FLIGHT frames
     * later, once begin_frame has waited this slot's fence. */
    flux_buffer *stats;
    bool stats_submitted;
    uint32_t stats_group_count;
} liquid_glass_filter_slot;

struct prism_liquid_glass_filter {
    atomic_uint ref_count;
    flux_device *device; /* retained; slot images hold weak device refs */
    /* Indexed by storage class: [0] rgba8, [1] rgba16f (ADR-0069). */
    flux_compute_pipeline *glass_pipelines[2]; /* lazily built on first apply */
    flux_compute_pipeline *clear_pipelines[2];
    flux_compute_pipeline *stats_pipeline;
    liquid_glass_filter_slot slots[FLUX_MAX_FRAMES_IN_FLIGHT];
};

/* ------------------------------------------------------------------ */
/*  Barrier helpers (raw Vulkan over flux_image_vk_image)             */
/* ------------------------------------------------------------------ */

/* Emit a compute-write → compute-read barrier on `image`, no layout
 * transition (image stays in GENERAL). Makes the output sampleable by any
 * later shader stage. */
static void barrier_compute_write_to_read(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask =
            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_READ_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* A reusable frame-slot image may have been sampled by the slot's previous
 * submission. begin_frame waited that slot's fence; this barrier expresses
 * the device-side read/write dependency before the next compute overwrite. */
static void barrier_reuse_to_compute_write(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask =
            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* Groups source-over the persistent storage image. Make an earlier group's
 * write visible to both imageLoad and imageStore in the next group; a
 * write-only dependency lets a later shadow replace the body below it
 * instead of compositing over it. */
static void barrier_compute_write_to_read_write(VkCommandBuffer cmd, VkImage image) {
    VkImageMemoryBarrier2 barrier = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_GENERAL,
        .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .image = image,
        .subresourceRange =
            {
                .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                .levelCount = 1,
                .layerCount = 1,
            },
    };
    VkDependencyInfo info = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &barrier,
    };
    vkCmdPipelineBarrier2(cmd, &info);
}

/* Make a stats-buffer compute write visible to the next submission's
 * compute read/write on the same buffer. Host visibility needs no barrier
 * here: the slot's frame fence plus the HOST_COHERENT mapping cover the
 * CPU readback path. */
static void barrier_stats_write_to_compute(VkCommandBuffer cmd, VkBuffer buffer) {
    VkBufferMemoryBarrier2 b = {
        .sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .dstAccessMask = VK_ACCESS_2_SHADER_STORAGE_READ_BIT | VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .buffer = buffer,
        .offset = 0,
        .size = VK_WHOLE_SIZE,
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .bufferMemoryBarrierCount = 1,
        .pBufferMemoryBarriers = &b,
    };
    vkCmdPipelineBarrier2(cmd, &di);
}

/* ------------------------------------------------------------------ */
/*  Filter lifecycle                                                  */
/* ------------------------------------------------------------------ */

flux_result prism_liquid_glass_filter_create(flux_device *device, prism_liquid_glass_filter **out) {
    if (!device || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out = nullptr;
    prism_liquid_glass_filter *filter = calloc(1, sizeof(*filter));
    if (!filter)
        return FLUX_ERROR_OUT_OF_MEMORY;
    atomic_init(&filter->ref_count, 1u);
    filter->device = flux_device_retain(device);
    *out = filter;
    return FLUX_OK;
}

prism_liquid_glass_filter *prism_liquid_glass_filter_retain(prism_liquid_glass_filter *filter) {
    if (filter)
        atomic_fetch_add_explicit(&filter->ref_count, 1u, memory_order_relaxed);
    return filter;
}

void prism_liquid_glass_filter_release(prism_liquid_glass_filter *filter) {
    if (!filter)
        return;
    if (atomic_fetch_sub_explicit(&filter->ref_count, 1u, memory_order_acq_rel) != 1u)
        return;
    flux_device *device = filter->device;
    for (uint32_t i = 0; i < FLUX_MAX_FRAMES_IN_FLIGHT; ++i) {
        if (filter->slots[i].output)
            flux_image_release(filter->slots[i].output);
        if (filter->slots[i].stats)
            flux_buffer_release(filter->slots[i].stats);
    }
    /* Pipelines are destroyed inline by flux; the header's release
     * contract (all referencing GPU work completed) covers this. */
    for (int i = 0; i < 2; ++i) {
        if (filter->glass_pipelines[i])
            flux_compute_pipeline_release(filter->glass_pipelines[i]);
        if (filter->clear_pipelines[i])
            flux_compute_pipeline_release(filter->clear_pipelines[i]);
    }
    if (filter->stats_pipeline)
        flux_compute_pipeline_release(filter->stats_pipeline);
    free(filter);
    flux_device_release(device);
}

static flux_result liquid_glass_ensure_stats_buffer(prism_liquid_glass_filter *filter,
                                                    liquid_glass_filter_slot *slot) {
    if (slot->stats)
        return FLUX_OK;
    flux_buffer_desc bdesc = FLUX_BUFFER_DESC_INIT;
    bdesc.size = PRISM_STATS_BYTES;
    bdesc.usage = FLUX_BUFFER_USAGE_STORAGE;
    /* HOST_VISIBLE is HOST_COHERENT in flux: the shader's writes are
     * visible to the CPU after the slot's fence, no flush/invalidate. */
    bdesc.location = FLUX_BUFFER_HOST_VISIBLE;
    bdesc.device_address = true; /* stats shader writes via buffer reference */
    return flux_buffer_create(filter->device, &bdesc, &slot->stats);
}

static flux_result liquid_glass_ensure_slot(prism_liquid_glass_filter *filter, uint32_t index,
                                            const flux_image *input, bool need_stats) {
    liquid_glass_filter_slot *slot = &filter->slots[index];
    uint32_t width = flux_image_width(input);
    uint32_t height = flux_image_height(input);
    flux_format format = prism_output_format(input);
    if (slot->output && slot->width == width && slot->height == height && slot->format == format)
        return need_stats ? liquid_glass_ensure_stats_buffer(filter, slot) : FLUX_OK;
    if (slot->output)
        flux_image_release(slot->output);
    if (slot->stats)
        flux_buffer_release(slot->stats);
    *slot = (liquid_glass_filter_slot){0};
    flux_result r =
        flux_image_create_compute_writable(filter->device, width, height, format, &slot->output);
    if (r != FLUX_OK)
        return r;
    slot->width = width;
    slot->height = height;
    slot->format = format;
    if (need_stats) {
        r = liquid_glass_ensure_stats_buffer(filter, slot);
        if (r != FLUX_OK)
            return r;
    }
    return FLUX_OK;
}

/* The material pipelines are per-filter and lazily built: prism has no
 * per-device module state of its own, and the filter contract already
 * requires callers to serialize per device. Pipelines are per storage
 * class (rgba8 / rgba16f); the stats shader samples only and is shared. */
static flux_result liquid_glass_ensure_pipelines(prism_liquid_glass_filter *filter, bool is16f,
                                                 bool need_clear, bool need_glass,
                                                 bool need_stats) {
    const int cls = is16f ? 1 : 0;
    if (need_clear && !filter->clear_pipelines[cls]) {
        flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
        pdesc.spirv = (const uint32_t *)(is16f ? storage_clear_16f_spv : storage_clear_spv);
        pdesc.spirv_word_count =
            (is16f ? sizeof(storage_clear_16f_spv) : sizeof(storage_clear_spv)) / sizeof(uint32_t);
        pdesc.entry_point = "main";
        pdesc.push_constant_bytes = sizeof(storage_clear_push);
        flux_result r =
            flux_compute_pipeline_create(filter->device, &pdesc, &filter->clear_pipelines[cls]);
        if (r != FLUX_OK)
            return r;
    }
    if (need_glass && !filter->glass_pipelines[cls]) {
        flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
        pdesc.spirv = (const uint32_t *)(is16f ? liquid_glass_16f_spv : liquid_glass_spv);
        pdesc.spirv_word_count =
            (is16f ? sizeof(liquid_glass_16f_spv) : sizeof(liquid_glass_spv)) / sizeof(uint32_t);
        pdesc.entry_point = "main";
        pdesc.push_constant_bytes = sizeof(liquid_glass_push);
        flux_result r =
            flux_compute_pipeline_create(filter->device, &pdesc, &filter->glass_pipelines[cls]);
        if (r != FLUX_OK)
            return r;
    }
    if (need_stats && !filter->stats_pipeline) {
        flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
        pdesc.spirv = (const uint32_t *)backdrop_stats_spv;
        pdesc.spirv_word_count = sizeof(backdrop_stats_spv) / sizeof(uint32_t);
        pdesc.entry_point = "main";
        pdesc.push_constant_bytes = sizeof(backdrop_stats_push);
        flux_result r =
            flux_compute_pipeline_create(filter->device, &pdesc, &filter->stats_pipeline);
        if (r != FLUX_OK)
            return r;
    }
    return FLUX_OK;
}

/* ------------------------------------------------------------------ */
/*  Apply                                                             */
/* ------------------------------------------------------------------ */

static bool valid_liquid_glass_desc(const prism_liquid_glass_desc *desc) {
    if (desc->type != PRISM_TYPE_LIQUID_GLASS_DESC || !desc->input || !desc->blurred_input ||
        desc->group_count > LIQUID_GLASS_MAX_GROUPS || (desc->group_count > 0u && !desc->groups))
        return false;
    if (!isfinite(desc->refraction) || !isfinite(desc->chromatic_aberration) ||
        !isfinite(desc->saturation) || !isfinite(desc->brightness) || !isfinite(desc->edge_width) ||
        !isfinite(desc->rim_light) || !isfinite(desc->light_direction.x) ||
        !isfinite(desc->light_direction.y) || !isfinite(desc->opacity) ||
        !isfinite(desc->size_reference) || !isfinite(desc->size_scale_min) ||
        !isfinite(desc->tint_strength) || !isfinite(desc->frost_strength))
        return false;
    for (uint32_t i = 0; i < desc->group_count; ++i) {
        if (!liquid_glass_group_is_valid(&desc->groups[i]))
            return false;
    }
    return true;
}

static void record_storage_clear_regions(prism_liquid_glass_filter *filter, VkCommandBuffer command,
                                         flux_image *output, const liquid_glass_region *regions,
                                         uint32_t region_count, bool is16f) {
    flux_compute_pipeline *clear_pipeline = filter->clear_pipelines[is16f ? 1 : 0];
    for (uint32_t i = 0; i < region_count; ++i) {
        liquid_glass_region region = regions[i];
        storage_clear_push push = {
            .output_handle = flux_image_bindless_storage_handle(output),
            .width = flux_image_width(output),
            .height = flux_image_height(output),
            .origin_x = region.x,
            .origin_y = region.y,
            .region_width = region.width,
            .region_height = region.height,
        };
        uint32_t gx = (region.width + PRISM_GLASS_WG - 1u) / PRISM_GLASS_WG;
        uint32_t gy = (region.height + PRISM_GLASS_WG - 1u) / PRISM_GLASS_WG;
        flux_compute_dispatch(command, clear_pipeline, &push, sizeof(push), gx, gy, 1u);
    }
}

flux_result prism_liquid_glass_filter_apply(prism_liquid_glass_filter *filter, flux_frame *frame,
                                            const prism_liquid_glass_desc *desc, flux_image **out) {
    if (!filter || !frame || !desc || !out)
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out = nullptr;
    if (!valid_liquid_glass_desc(desc))
        return FLUX_ERROR_INVALID_ARGUMENT;
    if (flux_frame_get_state(frame) != FLUX_FRAME_STATE_RECORDING ||
        flux_frame_has_active_pass(frame))
        return FLUX_ERROR_INVALID_STATE;
    flux_image *input = desc->input;
    flux_image *blurred = desc->blurred_input;
    if (flux_frame_device(frame) != filter->device || flux_image_device(input) != filter->device ||
        flux_image_device(blurred) != filter->device)
        return FLUX_ERROR_INVALID_ARGUMENT;
    /* ADR-0069: 8-bit SDR inputs keep the historic RGBA8 path (blurred
     * input is the flux blur filter's RGBA8 output); 16F working-space
     * inputs run the material in 16F end to end, and the blurred input
     * must be the matching 16F blur output. */
    const bool is16f = flux_image_format(input) == FLUX_FORMAT_RGBA16_SFLOAT;
    const flux_format want_blur = is16f ? FLUX_FORMAT_RGBA16_SFLOAT : FLUX_FORMAT_RGBA8_UNORM;
    if (flux_image_width(input) != flux_image_width(blurred) ||
        flux_image_height(input) != flux_image_height(blurred) ||
        (flux_image_format(input) != FLUX_FORMAT_RGBA8_UNORM &&
         flux_image_format(input) != FLUX_FORMAT_BGRA8_UNORM && !is16f) ||
        flux_image_format(blurred) != want_blur ||
        flux_image_bindless_handle(input) == FLUX_BINDLESS_INVALID ||
        flux_image_bindless_handle(blurred) == FLUX_BINDLESS_INVALID)
        return FLUX_ERROR_UNSUPPORTED;
    uint32_t index = flux_frame_index(frame);
    if (index >= FLUX_MAX_FRAMES_IN_FLIGHT)
        return FLUX_ERROR_OUT_OF_RANGE;
    flux_result result = liquid_glass_ensure_slot(filter, index, input, desc->group_count > 0u);
    if (result != FLUX_OK)
        return result;

    uint32_t image_width = flux_image_width(input);
    uint32_t image_height = flux_image_height(input);
    liquid_glass_filter_slot *slot = &filter->slots[index];
    liquid_glass_region current[LIQUID_GLASS_MAX_GROUPS];
    uint32_t current_group_indices[LIQUID_GLASS_MAX_GROUPS];
    uint32_t current_count = 0u;
    for (uint32_t i = 0; i < desc->group_count; ++i) {
        const prism_liquid_glass_group *group = &desc->groups[i];
        /* The body's shadow reaches its downward offset plus the falloff. */
        float shadow_reach = group->shadow_alpha > 0.0f ? fmaxf(group->shadow_offset_y, 0.0f) +
                                                              2.0f * fmaxf(group->shadow_blur, 0.0f)
                                                        : 0.0f;
        liquid_glass_region region;
        if (!liquid_glass_group_dispatch_bounds(group, shadow_reach, image_width, image_height,
                                                &region))
            continue;
        current[current_count] = region;
        current_group_indices[current_count] = i;
        ++current_count;
    }

    liquid_glass_region clear_regions[LIQUID_GLASS_MAX_CLEAR_REGIONS];
    uint32_t clear_count = 0u;
    if (!liquid_glass_build_clear_regions(
            slot->initialized, image_width, image_height, slot->previous, slot->previous_count,
            current, current_count, clear_regions, LIQUID_GLASS_MAX_CLEAR_REGIONS, &clear_count))
        return FLUX_ERROR_INVALID_STATE;

    result = liquid_glass_ensure_pipelines(filter, is16f, clear_count > 0u, current_count > 0u,
                                           desc->group_count > 0u);
    if (result != FLUX_OK)
        return result;

    VkCommandBuffer command = flux_frame_vk_command_buffer(frame);
    VkImage output_image = flux_image_vk_image(slot->output);
    if (clear_count > 0u) {
        if (slot->initialized)
            barrier_reuse_to_compute_write(command, output_image);
        record_storage_clear_regions(filter, command, slot->output, clear_regions, clear_count,
                                     is16f);
        if (current_count > 0u)
            barrier_compute_write_to_read_write(command, output_image);
    }

    /* Backdrop statistics: one 16x16 workgroup per group reduces the
     * primary body's backdrop into (mean luminance, high-frequency energy)
     * for the frame-lagged CPU read. Off-screen bodies reduce an empty
     * rect, which the shader reports as zeros. Runs before the glass
     * dispatches; it shares only their sampled inputs. */
    if (desc->group_count > 0u) {
        uint64_t stats_address = flux_buffer_device_address(slot->stats);
        for (uint32_t i = 0; i < desc->group_count; ++i) {
            liquid_glass_region rect =
                liquid_glass_group_stats_bounds(&desc->groups[i], image_width, image_height);
            backdrop_stats_push spush = {
                .input_handle = flux_image_bindless_handle(input),
                .blurred_handle = flux_image_bindless_handle(blurred),
                .sampler_handle = flux_device_default_sampler_handle(filter->device),
                .width = image_width,
                .height = image_height,
                .rect_x = rect.x,
                .rect_y = rect.y,
                .rect_width = rect.width,
                .rect_height = rect.height,
                .group_index = i,
                .stats_address_lo = (uint32_t)(stats_address & 0xFFFFFFFFu),
                .stats_address_hi = (uint32_t)(stats_address >> 32u),
            };
            flux_compute_dispatch(command, filter->stats_pipeline, &spush, sizeof(spush), 1u, 1u,
                                  1u);
        }
        barrier_stats_write_to_compute(command, flux_buffer_vk_buffer(slot->stats));
    }

    bool dispatched = false;
    const prism_glass_policy policy = {
        .refraction = desc->refraction,
        .chromatic_aberration = desc->chromatic_aberration,
        .saturation = desc->saturation,
        .brightness = desc->brightness,
        .edge_width = desc->edge_width,
        .rim_light = desc->rim_light,
        .light_x = desc->light_direction.x,
        .light_y = desc->light_direction.y,
        .opacity = desc->opacity,
        .size_reference = desc->size_reference,
        .size_scale_min = desc->size_scale_min,
        .tint_strength = desc->tint_strength,
        .frost_strength = desc->frost_strength,
    };
    for (uint32_t i = 0; i < current_count; ++i) {
        const prism_liquid_glass_group *group = &desc->groups[current_group_indices[i]];
        liquid_glass_region region = current[i];
        if (dispatched)
            barrier_compute_write_to_read_write(command, output_image);
        prism_glass_record_group(command, filter->glass_pipelines[is16f ? 1 : 0], filter->device,
                                 input, blurred, slot->output, image_width, image_height, region,
                                 group, &policy);
        dispatched = true;
    }
    /* Both the transparent region clear and liquid material are compute
     * storage writes. Make the persistent output visible to its following
     * Canvas sample, including a clear-only apply after all groups disappear. */
    if (clear_count > 0u || dispatched)
        barrier_compute_write_to_read(command, output_image);

    if (current_count > 0u)
        memcpy(slot->previous, current, current_count * sizeof(current[0]));
    slot->previous_count = current_count;
    slot->initialized = true;
    slot->stats_submitted = true;
    /* A zero-group apply submits no stats; the frame-lagged read then
     * honestly reports zero groups for this slot's last submission. */
    slot->stats_group_count = desc->group_count;
    *out = slot->output;
    return FLUX_OK;
}

flux_result prism_liquid_glass_filter_stats(prism_liquid_glass_filter *filter, flux_frame *frame,
                                            prism_backdrop_stat *out, uint32_t max_groups,
                                            uint32_t *out_count) {
    if (!filter || !frame || !out_count || (max_groups > 0u && !out))
        return FLUX_ERROR_INVALID_ARGUMENT;
    *out_count = 0u;
    if (flux_frame_device(frame) != filter->device)
        return FLUX_ERROR_INVALID_ARGUMENT;
    /* The mapped buffer is stable only while this frame records: its
     * begin_frame waited the slot's fence. */
    if (flux_frame_get_state(frame) != FLUX_FRAME_STATE_RECORDING)
        return FLUX_ERROR_INVALID_STATE;
    uint32_t index = flux_frame_index(frame);
    if (index >= FLUX_MAX_FRAMES_IN_FLIGHT)
        return FLUX_ERROR_OUT_OF_RANGE;
    const liquid_glass_filter_slot *slot = &filter->slots[index];
    if (!slot->stats_submitted || !slot->stats)
        return FLUX_ERROR_INVALID_STATE;
    uint32_t count = slot->stats_group_count < max_groups ? slot->stats_group_count : max_groups;
    if (count > 0u)
        memcpy(out, flux_buffer_mapped(slot->stats), count * sizeof(*out));
    *out_count = count;
    return FLUX_OK;
}
