#!/bin/sh
# check-tidy.sh — run clang-tidy over the library translation units.
#
# Scope: libs/**/src/*.c (the shipped code). Tests are excluded: they
# deliberately do things libraries must not (globals, asserts with side
# effects). Headers are analyzed via HeaderFilterRegex in .clang-tidy.
#
# Baseline policy (no legacy debt): the check runs on every file; a new
# warning fails CI. Existing warnings are fixed, not baselined away —
# the codebase is small enough that this stays true.

set -e
cd "$(dirname "$0")/.."

CLANG_TIDY=${CLANG_TIDY:-clang-tidy}
BUILD_DIR=${1:-build-tidy}

if [ ! -d "$BUILD_DIR" ]; then
    CC=clang meson setup "$BUILD_DIR" -Dtests=true -Dexamples=false \
      --buildtype=debug -Dfreetype2:harfbuzz=disabled -Dharfbuzz:cairo=disabled
fi

# Shader headers (spv.h) are generated by the build; prism TUs include
# them, so compile everything once before analyzing.
meson compile -C "$BUILD_DIR" >/dev/null

# compile_commands.json lives in the build dir; clang-tidy consumes it.
# Windows-only TUs (windows.h / DirectWrite) are compiled by the zig
# cross-check in ci-cross instead — clang-tidy here runs on Linux and
# cannot see those headers.
SOURCES=$(find libs -name '*.c' -path '*/src/*' | grep -v subprojects | grep -vE '_(win32|directwrite|cocoa|coretext)\.c$' | sort)

FAILED=0
for src in $SOURCES; do
    if ! "$CLANG_TIDY" -p "$BUILD_DIR" "$src" 2>/dev/null | grep -qE 'warning:|error:'; then
        continue
    fi
    echo "=== $src"
    "$CLANG_TIDY" -p "$BUILD_DIR" "$src" 2>/dev/null | grep -E 'warning:|error:' || true
    FAILED=1
done

if [ "$FAILED" -ne 0 ]; then
    echo ""
    echo "clang-tidy found issues above. Fix them; do not silence without a reason."
    exit 1
fi
echo "clang-tidy clean ($BUILD_DIR)"
