#!/usr/bin/env python3
"""Emit a C header holding a content hash of the given SPIR-V binaries.

Why this exists: ccache (observed on 4.13.6) does not hash files pulled
in via C23 `#embed`, so editing a shader left the compiled library with
the previous object — the build was green while running stale bytecode.
Ninja's depfiles are correct (GCC 16 lists #embed inputs), the cache
key is not. Every #embed-consuming translation unit includes this
generated header unconditionally, which puts the shader bytes' hash
into the preprocessed source and therefore into the cache key.

Usage: shader_manifest.py <out.h> <in.spv>...

Revocation: when a ccache release hashes `#embed` inputs into its
cache key (check with a shader edit under a warm cache), delete this
script, the manifest custom_target in libs/flux/meson.build (and the
prism/examples/test twins), and the unconditional includes of the
generated header in renderer.c / scene.c / effect.c. Until then this
is load-bearing: removing it silently reintroduces stale-shader
builds for every ccache user.
"""
import hashlib
import sys


def main() -> int:
    out = sys.argv[1]
    ins = sys.argv[2:]
    digest = hashlib.sha256()
    for path in ins:
        digest.update(path.encode())
        with open(path, "rb") as f:
            digest.update(f.read())
    with open(out, "w") as f:
        f.write("/* Generated by tools/shader_manifest.py — do not edit. */\n")
        f.write('static const char flux_shader_manifest[] = "%s";\n' % digest.hexdigest())
    return 0


if __name__ == "__main__":
    sys.exit(main())
