#!/usr/bin/env python3
"""Generate a C header holding a SPIR-V binary's bytes.

Fallback for the C23 `#embed` shader-baking path: MSVC cl and Apple
Clang have no `#embed`, so meson runs this script per shader and the C
sources `#include` the generated header instead (see the
FLUX_*_SHADER_EMBED blocks in renderer.c / effect.c / scene.c).

The generated array carries the same name, element type (unsigned char,
alignas uint32_t) and byte content as the `#embed` path, so call sites
are identical in both configurations.

Usage: spv2h.py <input.spv> <output.h> <array_name>
"""

import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    src_path, dst_path, name = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(src_path, "rb") as src:
        data = src.read()
    # SPIR-V is a stream of 32-bit words; a non-multiple means the file
    # is truncated or not SPIR-V at all.
    assert len(data) % 4 == 0, f"{src_path}: size {len(data)} is not 4-byte aligned"
    assert len(data) >= 4 and int.from_bytes(data[:4], "little") == 0x07230203, (
        f"{src_path}: bad SPIR-V magic"
    )

    guard = "FLUX_GENERATED_" + name.upper() + "_H"
    lines = [
        f"/* Generated by tools/spv2h.py from {src_path.rsplit('/', 1)[-1]}. Do not edit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"alignas(uint32_t) static const unsigned char {name}[] = {{",
    ]
    for off in range(0, len(data), 12):
        chunk = data[off : off + 12]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    lines += ["};", "", f"#endif /* {guard} */", ""]

    with open(dst_path, "w", encoding="utf-8") as dst:
        dst.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
