/*
 * Validation-clean assertion. Forces the Vulkan validation layers ON
 * and installs a log callback that counts WARN/ERROR messages.
 * Exercises a representative lifecycle (device + bindless + image +
 * compute pipeline + dispatch) and fails if any validation message
 * fired. Skips if validation isn't available on the test host.
 */
#include "test_helpers.h"
#include <flux/compute.h>
#include <flux/flux.h>
#include <flux/vulkan.h>

#include <stdalign.h>
#include <stdatomic.h>
#include <string.h>

/* Shader bytecode: C23 #embed primarily; toolchains without it (MSVC cl,
 * Apple Clang) include the spv2h.py-generated header instead (same
 * array). FLUX_SHADER_NO_EMBED forces the fallback for testing. */
#if defined(__has_embed) && !defined(FLUX_SHADER_NO_EMBED)
#if __has_embed("fill_pattern.comp.spv")
#define TEST_SHADERS_EMBED 1
#endif
#endif

#ifdef TEST_SHADERS_EMBED
alignas(uint32_t) static const unsigned char fill_spv[] = {
#embed "fill_pattern.comp.spv"
};
#else
#include "fill_pattern_comp_spv.h" /* generated by tools/spv2h.py; same array */
#endif

static atomic_uint g_validation_errors = 0;
static atomic_uint g_validation_warns = 0;

static void counting_logger(flux_log_level level, const char *file, int line, const char *fmt,
                            const char *msg, void *user) {
    (void)file;
    (void)line;
    (void)fmt;
    (void)user;
    if (level == FLUX_LOG_ERROR)
        atomic_fetch_add(&g_validation_errors, 1u);
    if (level == FLUX_LOG_WARN)
        atomic_fetch_add(&g_validation_warns, 1u);
    /* Echo so failures are diagnosable. */
    if (level >= FLUX_LOG_WARN && msg)
        fprintf(stderr, "[flux validation] %s\n", msg);
}

#define COUNT 256u
#define WORKGROUP 64u
#define BYTES (COUNT * sizeof(float))

typedef struct push_constants {
    uint64_t out_buffer_address;
    uint32_t count;
    uint32_t _pad;
} push_constants;

int main(void) {
    flux_device *d = test_helpers_make_validation_device(counting_logger);
    if (!d) {
        /* Validation unavailable (no validation layer on the host).
         * Don't fail the test; that's an environment concern. */
        fprintf(stderr, "test_validation: validation not available; skipping\n");
        TEST_SUMMARY();
    }

    /* --- bindless lifecycle via flux_image_create --- */
    {
        flux_image_desc desc = FLUX_IMAGE_DESC_INIT;
        desc.width = 8;
        desc.height = 8;
        desc.format = FLUX_FORMAT_RGBA8_UNORM;
        flux_image *im = nullptr;
        EXPECT(flux_image_create(d, &desc, &im) == FLUX_OK);
        flux_image_release(im);
    }

    /* --- compute pipeline + dispatch --- */
    VkDevice vk = flux_device_vk_device(d);
    VkQueue queue = flux_device_vk_graphics_queue(d);
    uint32_t qfam = flux_device_vk_graphics_family(d);

    VkBuffer buffer = VK_NULL_HANDLE;
    VkDeviceMemory memory = VK_NULL_HANDLE;
    void *mapped = nullptr;
    {
        VkBufferCreateInfo bci = {
            .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
            .size = BYTES,
            .usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,
            .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
        };
        EXPECT(vkCreateBuffer(vk, &bci, nullptr, &buffer) == VK_SUCCESS);

        VkMemoryRequirements mr;
        vkGetBufferMemoryRequirements(vk, buffer, &mr);
        uint32_t mt = test_helpers_find_memory_type(d, mr.memoryTypeBits,
                                                    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                                        VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
        VkMemoryAllocateFlagsInfo afi = {
            .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO,
            .flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT,
        };
        VkMemoryAllocateInfo mai = {
            .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
            .pNext = &afi,
            .allocationSize = mr.size,
            .memoryTypeIndex = mt,
        };
        EXPECT(vkAllocateMemory(vk, &mai, nullptr, &memory) == VK_SUCCESS);
        vkBindBufferMemory(vk, buffer, memory, 0);
        vkMapMemory(vk, memory, 0, VK_WHOLE_SIZE, 0, &mapped);
    }

    VkBufferDeviceAddressInfo bdai = {
        .sType = VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO,
        .buffer = buffer,
    };
    uint64_t baddr = vkGetBufferDeviceAddress(vk, &bdai);

    flux_compute_pipeline_desc pdesc = FLUX_COMPUTE_PIPELINE_DESC_INIT;
    pdesc.spirv = (const uint32_t *)fill_spv;
    pdesc.spirv_word_count = sizeof(fill_spv) / sizeof(uint32_t);
    pdesc.entry_point = "main";
    pdesc.push_constant_bytes = sizeof(push_constants);
    flux_compute_pipeline *pipe = nullptr;
    EXPECT(flux_compute_pipeline_create(d, &pdesc, &pipe) == FLUX_OK);

    VkCommandPool pool = VK_NULL_HANDLE;
    VkCommandPoolCreateInfo pci = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
        .queueFamilyIndex = qfam,
        .flags = VK_COMMAND_POOL_CREATE_TRANSIENT_BIT,
    };
    vkCreateCommandPool(vk, &pci, nullptr, &pool);

    VkCommandBuffer cmd;
    VkCommandBufferAllocateInfo cbai = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool = pool,
        .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        .commandBufferCount = 1,
    };
    vkAllocateCommandBuffers(vk, &cbai, &cmd);

    VkCommandBufferBeginInfo cbbi = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
        .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT,
    };
    vkBeginCommandBuffer(cmd, &cbbi);

    push_constants pc = {.out_buffer_address = baddr, .count = COUNT};
    flux_compute_dispatch(cmd, pipe, &pc, sizeof(pc), (COUNT + WORKGROUP - 1) / WORKGROUP, 1, 1);

    VkMemoryBarrier2 mb = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        .srcAccessMask = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_HOST_BIT,
        .dstAccessMask = VK_ACCESS_2_HOST_READ_BIT,
    };
    VkDependencyInfo di = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .memoryBarrierCount = 1,
        .pMemoryBarriers = &mb,
    };
    vkCmdPipelineBarrier2(cmd, &di);
    vkEndCommandBuffer(cmd);

    VkCommandBufferSubmitInfo cbsi = {.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_SUBMIT_INFO,
                                      .commandBuffer = cmd};
    VkSubmitInfo2 si = {
        .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO_2,
        .commandBufferInfoCount = 1,
        .pCommandBufferInfos = &cbsi,
    };
    VkFence fence;
    VkFenceCreateInfo fci = {.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    vkCreateFence(vk, &fci, nullptr, &fence);
    vkQueueSubmit2(queue, 1, &si, fence);
    vkWaitForFences(vk, 1, &fence, VK_TRUE, UINT64_MAX);
    vkDestroyFence(vk, fence, nullptr);

    vkDestroyCommandPool(vk, pool, nullptr);
    flux_compute_pipeline_release(pipe);
    if (mapped)
        vkUnmapMemory(vk, memory);
    if (memory)
        vkFreeMemory(vk, memory, nullptr);
    if (buffer)
        vkDestroyBuffer(vk, buffer, nullptr);
    flux_device_release(d);

    /* Final assertion: zero validation errors, zero validation warnings.
     * If this trips, the failing message has already been printed via
     * counting_logger above. */
    unsigned errs = atomic_load(&g_validation_errors);
    unsigned warns = atomic_load(&g_validation_warns);
    if (errs || warns) {
        fprintf(stderr, "validation: %u errors, %u warnings\n", errs, warns);
    }
    EXPECT(errs == 0);
    EXPECT(warns == 0);

    TEST_SUMMARY();
}
